/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { Category } from "./category";

/**
 * Budget
 */
export interface Budget {
  /** 予算ID */
  id: number;
  /** ユーザーID */
  user_id: number;
  /** カテゴリID */
  category_id: number;
  /** カテゴリ情報 */
  category: Category;
  /** 予算額 */
  amount: number;
  /**
   * 対象月（YYYY-MM形式）
   * @minLength 7
   * @maxLength 7
   */
  month: string;
  /** 作成日時 */
  created_at: Date;
  /** 更新日時 */
  updated_at: Date;
}
