/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * カテゴリタイプ
 */
export type CategoryType = (typeof CategoryType)[keyof typeof CategoryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryType = {
  income: "income",
  expense: "expense",
} as const;
