/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * Category
 */
export interface Category {
  /** カテゴリID */
  id: number;
  /** ユーザーID */
  user_id: number;
  /**
   * カテゴリ名
   * @maxLength 100
   */
  name: string;
  /**
   * カテゴリの色
   * @maxLength 20
   */
  color: string;
  /** 作成日時 */
  created_at: Date;
  /** 更新日時 */
  updated_at: Date;
}
