/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { CategoryType } from "./categoryType";

/**
 * Create Category Input
 */
export interface CreateCategoryInput {
  /**
   * カテゴリ名
   * @maxLength 100
   */
  name: string;
  /** カテゴリタイプ（収入/支出） */
  type: CategoryType;
  /**
   * カテゴリの色
   * @maxLength 20
   */
  color: string;
}
