/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * Create Budget Input
 */
export interface CreateBudgetInput {
  /** カテゴリID */
  category_id: number;
  /**
   * 予算額
   * @minimum 1
   */
  amount: number;
  /**
   * 対象月（YYYY-MM形式）
   * @minLength 7
   * @maxLength 7
   */
  month: string;
}
