/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { Transaction } from "./transaction";

/**
 * Create Transaction Response
 */
export interface CreateTransactionResponse {
  transaction: Transaction;
}
