/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { Budget } from "./budget";

/**
 * Create Budget Response
 */
export interface CreateBudgetResponse {
  budget: Budget;
}
