/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { TransactionType } from "./transactionType";

/**
 * Create Transaction Input
 */
export interface CreateTransactionInput {
  /** カテゴリID */
  category_id: number;
  /** 取引タイプ（収入/支出） */
  type: TransactionType;
  /**
   * 金額
   * @minimum 1
   */
  amount: number;
  /** 取引日 */
  date: Date;
  /**
   * 説明
   * @maxLength 255
   */
  description?: string;
}
