/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { ErrorStatus } from "./errorStatus";
import type { ErrorInfo } from "./errorInfo";

/**
 * エラーレスポンス
 */
export interface ErrorResponse {
  /** HTTPステータスコード */
  code: number;
  /** 人間が読めるエラーメッセージ */
  message: string;
  /** 標準エラーステータス */
  status: ErrorStatus;
  /** 詳細なエラー情報 */
  details?: ErrorInfo[];
}
