/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * 標準エラーステータス（Google API Standard準拠）
 */
export type ErrorStatus = (typeof ErrorStatus)[keyof typeof ErrorStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorStatus = {
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  FAILED_PRECONDITION: "FAILED_PRECONDITION",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  NOT_FOUND: "NOT_FOUND",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INTERNAL: "INTERNAL",
} as const;
