/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * 型識別子
 */
export type ErrorInfoType = (typeof ErrorInfoType)[keyof typeof ErrorInfoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorInfoType = {
  ErrorInfo: "ErrorInfo",
} as const;
