/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { ErrorInfoType } from "./errorInfoType";
import type { ErrorReason } from "./errorReason";
import type { ErrorInfoMetadata } from "./errorInfoMetadata";

/**
 * エラー詳細情報
 */
export interface ErrorInfo {
  /** 型識別子 */
  "@type": ErrorInfoType;
  /** エラーの理由 */
  reason: ErrorReason;
  /** エラーが発生したドメイン */
  domain: string;
  /** 追加のメタデータ（キー・バリュー） */
  metadata?: ErrorInfoMetadata;
}
