/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { Budget } from "./budget";

/**
 * Fetch Budget List Response
 */
export interface FetchBudgetListResponse {
  budgets: Budget[];
}
