/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

export type GetBudgetsParams = {
  /**
   * 対象月（YYYY-MM形式）
   */
  month?: string;
  /**
   * カテゴリID
   */
  category_id?: number;
};
