/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { CategoryType } from "./categoryType";

export type GetTransactionsParams = {
  /**
   * 開始日（YYYY-MM-DD形式）
   */
  start_date?: string;
  /**
   * 終了日（YYYY-MM-DD形式）
   */
  end_date?: string;
  /**
   * カテゴリタイプ（income/expense）
   */
  type?: CategoryType;
  /**
   * カテゴリID
   */
  category_id?: number;
};
