/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { TransactionType } from "./transactionType";

export type GetTransactionsParams = {
  /**
   * 開始日（YYYY-MM-DD形式）
   */
  start_date?: Date;
  /**
   * 終了日（YYYY-MM-DD形式）
   */
  end_date?: Date;
  /**
   * 取引タイプ（income/expense）
   */
  type?: TransactionType;
  /**
   * カテゴリID
   */
  category_id?: number;
};
