/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { Category } from "./category";
import type { TransactionType } from "./transactionType";

/**
 * Transaction
 */
export interface Transaction {
  /** 取引ID */
  id: number;
  /** ユーザーID */
  user_id: number;
  /** カテゴリID */
  category_id: number;
  /** カテゴリ情報 */
  category: Category;
  /** 取引タイプ（収入/支出） */
  type: TransactionType;
  /** 金額 */
  amount: number;
  /** 取引日 */
  date: Date;
  /**
   * 説明
   * @maxLength 255
   */
  description: string;
  /** 作成日時 */
  created_at: Date;
  /** 更新日時 */
  updated_at: Date;
}
