/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * Update Category Input (partial update)
 */
export interface UpdateCategoryInput {
  /**
   * カテゴリ名
   * @maxLength 100
   */
  name?: string;
  /**
   * カテゴリの色
   * @maxLength 20
   */
  color?: string;
}
