/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import type { Category } from "./category";

/**
 * Update Category Response
 */
export interface UpdateCategoryResponse {
  category: Category;
}
