/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * User CheckSignedIn Response
 */
export interface UserUserCheckSignedInResponse {
  /** ログイン状態 */
  is_signed_in: boolean;
}
