/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */

/**
 * User Sign Up Response
 */
export interface UserUserSignUpResponse {
  /** メッセージ */
  message: string;
}
