// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ErrorInfoType.
const (
	ErrorInfoTypeErrorInfo ErrorInfoType = "ErrorInfo"
)

// Defines values for ErrorReason.
const (
	BUDGETALREADYEXISTS    ErrorReason = "BUDGET_ALREADY_EXISTS"
	BUDGETNOTFOUND         ErrorReason = "BUDGET_NOT_FOUND"
	CATEGORYINUSE          ErrorReason = "CATEGORY_IN_USE"
	CATEGORYNOTFOUND       ErrorReason = "CATEGORY_NOT_FOUND"
	DATABASEERROR          ErrorReason = "DATABASE_ERROR"
	EMAILALREADYEXISTS     ErrorReason = "EMAIL_ALREADY_EXISTS"
	INVALIDAMOUNT          ErrorReason = "INVALID_AMOUNT"
	INVALIDBUDGETAMOUNT    ErrorReason = "INVALID_BUDGET_AMOUNT"
	INVALIDCATEGORYCOLOR   ErrorReason = "INVALID_CATEGORY_COLOR"
	INVALIDCATEGORYNAME    ErrorReason = "INVALID_CATEGORY_NAME"
	INVALIDCREDENTIALS     ErrorReason = "INVALID_CREDENTIALS"
	INVALIDDATE            ErrorReason = "INVALID_DATE"
	INVALIDEMAIL           ErrorReason = "INVALID_EMAIL"
	INVALIDMONTH           ErrorReason = "INVALID_MONTH"
	INVALIDPASSWORD        ErrorReason = "INVALID_PASSWORD"
	INVALIDTRANSACTIONTYPE ErrorReason = "INVALID_TRANSACTION_TYPE"
	TRANSACTIONNOTFOUND    ErrorReason = "TRANSACTION_NOT_FOUND"
	UNKNOWNERROR           ErrorReason = "UNKNOWN_ERROR"
	USERNOTFOUND           ErrorReason = "USER_NOT_FOUND"
)

// Defines values for ErrorStatus.
const (
	ALREADYEXISTS    ErrorStatus = "ALREADY_EXISTS"
	INTERNAL         ErrorStatus = "INTERNAL"
	INVALIDARGUMENT  ErrorStatus = "INVALID_ARGUMENT"
	NOTFOUND         ErrorStatus = "NOT_FOUND"
	PERMISSIONDENIED ErrorStatus = "PERMISSION_DENIED"
	UNAUTHENTICATED  ErrorStatus = "UNAUTHENTICATED"
)

// Defines values for TransactionType.
const (
	Expense TransactionType = "expense"
	Income  TransactionType = "income"
)

// Budget Budget
type Budget struct {
	// Amount 予算額
	Amount int32 `json:"amount"`

	// Category カテゴリ情報
	Category Category `json:"category"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Id 予算ID
	Id int32 `json:"id"`

	// Month 対象月（YYYY-MM形式）
	Month string `json:"month"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// Category Category
type Category struct {
	// Color カテゴリの色
	Color string `json:"color"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Id カテゴリID
	Id int32 `json:"id"`

	// Name カテゴリ名
	Name string `json:"name"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// CreateBudgetInput Create Budget Input
type CreateBudgetInput struct {
	// Amount 予算額
	Amount int32 `json:"amount"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// Month 対象月（YYYY-MM形式）
	Month string `json:"month"`
}

// CreateBudgetResponse Create Budget Response
type CreateBudgetResponse struct {
	// Budget Budget
	Budget Budget `json:"budget"`
}

// CreateCategoryInput Create Category Input
type CreateCategoryInput struct {
	// Color カテゴリの色
	Color string `json:"color"`

	// Name カテゴリ名
	Name string `json:"name"`
}

// CreateCategoryResponse Create Category Response
type CreateCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// CreateTransactionInput Create Transaction Input
type CreateTransactionInput struct {
	// Amount 金額
	Amount int32 `json:"amount"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// Date 取引日
	Date openapi_types.Date `json:"date"`

	// Description 説明
	Description *string `json:"description,omitempty"`

	// Type 取引タイプ（収入/支出）
	Type TransactionType `json:"type"`
}

// CreateTransactionResponse Create Transaction Response
type CreateTransactionResponse struct {
	// Transaction Transaction
	Transaction Transaction `json:"transaction"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// ErrorBody エラーレスポンスボディ
type ErrorBody struct {
	// Error エラーレスポンス
	Error ErrorResponse `json:"error"`
}

// ErrorInfo エラー詳細情報
type ErrorInfo struct {
	// Type 型識別子
	Type ErrorInfoType `json:"@type"`

	// Domain エラーが発生したドメイン
	Domain string `json:"domain"`

	// Metadata 追加のメタデータ（キー・バリュー）
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Reason エラーの理由
	Reason ErrorReason `json:"reason"`
}

// ErrorInfoType 型識別子
type ErrorInfoType string

// ErrorReason エラー理由の定数
type ErrorReason string

// ErrorResponse エラーレスポンス
type ErrorResponse struct {
	// Code HTTPステータスコード
	Code int32 `json:"code"`

	// Details 詳細なエラー情報
	Details *[]ErrorInfo `json:"details,omitempty"`

	// Message 人間が読めるエラーメッセージ
	Message string `json:"message"`

	// Status 標準エラーステータス
	Status ErrorStatus `json:"status"`
}

// ErrorStatus 標準エラーステータス（Google API Standard準拠）
type ErrorStatus string

// FetchBudgetListResponse Fetch Budget List Response
type FetchBudgetListResponse struct {
	Budgets []Budget `json:"budgets"`
}

// FetchBudgetResponse Fetch Budget Response
type FetchBudgetResponse struct {
	// Budget Budget
	Budget Budget `json:"budget"`
}

// FetchCategoryListsResponse Fetch Category Lists Response
type FetchCategoryListsResponse struct {
	Categories []Category `json:"categories"`
}

// FetchCategoryResponse Fetch Category Response
type FetchCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// FetchTransactionListResponse Fetch Transaction List Response
type FetchTransactionListResponse struct {
	Transactions []Transaction `json:"transactions"`
}

// FetchTransactionResponse Fetch Transaction Response
type FetchTransactionResponse struct {
	// Transaction Transaction
	Transaction Transaction `json:"transaction"`
}

// Transaction Transaction
type Transaction struct {
	// Amount 金額
	Amount int32 `json:"amount"`

	// Category カテゴリ情報
	Category Category `json:"category"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Date 取引日
	Date openapi_types.Date `json:"date"`

	// Description 説明
	Description string `json:"description"`

	// Id 取引ID
	Id int32 `json:"id"`

	// Type 取引タイプ（収入/支出）
	Type TransactionType `json:"type"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// TransactionType 取引タイプ
type TransactionType string

// UpdateBudgetInput Update Budget Input (partial update)
type UpdateBudgetInput struct {
	// Amount 予算額
	Amount *int32 `json:"amount,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `json:"category_id,omitempty"`

	// Month 対象月（YYYY-MM形式）
	Month *string `json:"month,omitempty"`
}

// UpdateBudgetResponse Update Budget Response
type UpdateBudgetResponse struct {
	// Budget Budget
	Budget Budget `json:"budget"`
}

// UpdateCategoryInput Update Category Input (partial update)
type UpdateCategoryInput struct {
	// Color カテゴリの色
	Color *string `json:"color,omitempty"`

	// Name カテゴリ名
	Name *string `json:"name,omitempty"`
}

// UpdateCategoryResponse Update Category Response
type UpdateCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// UpdateTransactionInput Update Transaction Input (partial update)
type UpdateTransactionInput struct {
	// Amount 金額
	Amount *int32 `json:"amount,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `json:"category_id,omitempty"`

	// Date 取引日
	Date *openapi_types.Date `json:"date,omitempty"`

	// Description 説明
	Description *string `json:"description,omitempty"`

	// Type 取引タイプ（収入/支出）
	Type *TransactionType `json:"type,omitempty"`
}

// UpdateTransactionResponse Update Transaction Response
type UpdateTransactionResponse struct {
	// Transaction Transaction
	Transaction Transaction `json:"transaction"`
}

// UserSignInInput Sign In Input
type UserSignInInput struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Password パスワード
	Password string `json:"password"`
}

// UserSignUpInput Sign Up Input
type UserSignUpInput struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Name ユーザー名
	Name string `json:"name"`

	// Password パスワード
	Password string `json:"password"`
}

// UserUserCheckSignedInResponse User CheckSignedIn Response
type UserUserCheckSignedInResponse struct {
	// IsSignedIn ログイン状態
	IsSignedIn bool `json:"is_signed_in"`
}

// UserUserSignInResponse User Sign In Response
type UserUserSignInResponse = map[string]interface{}

// UserUserSignUpResponse User Sign Up Response
type UserUserSignUpResponse struct {
	// Message メッセージ
	Message string `json:"message"`
}

// GetBudgetsParams defines parameters for GetBudgets.
type GetBudgetsParams struct {
	// Month 対象月（YYYY-MM形式）
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// GetTransactionsParams defines parameters for GetTransactions.
type GetTransactionsParams struct {
	// StartDate 開始日（YYYY-MM-DD形式）
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate 終了日（YYYY-MM-DD形式）
	EndDate *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`

	// Type 取引タイプ（income/expense）
	Type *TransactionType `form:"type,omitempty" json:"type,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// PostBudgetsJSONRequestBody defines body for PostBudgets for application/json ContentType.
type PostBudgetsJSONRequestBody = CreateBudgetInput

// PatchBudgetsIdJSONRequestBody defines body for PatchBudgetsId for application/json ContentType.
type PatchBudgetsIdJSONRequestBody = UpdateBudgetInput

// PostCategoriesJSONRequestBody defines body for PostCategories for application/json ContentType.
type PostCategoriesJSONRequestBody = CreateCategoryInput

// PatchCategoriesIdJSONRequestBody defines body for PatchCategoriesId for application/json ContentType.
type PatchCategoriesIdJSONRequestBody = UpdateCategoryInput

// PostTransactionsJSONRequestBody defines body for PostTransactions for application/json ContentType.
type PostTransactionsJSONRequestBody = CreateTransactionInput

// PatchTransactionsIdJSONRequestBody defines body for PatchTransactionsId for application/json ContentType.
type PatchTransactionsIdJSONRequestBody = UpdateTransactionInput

// PostUsersSignInJSONRequestBody defines body for PostUsersSignIn for application/json ContentType.
type PostUsersSignInJSONRequestBody = UserSignInInput

// PostUsersSignUpJSONRequestBody defines body for PostUsersSignUp for application/json ContentType.
type PostUsersSignUpJSONRequestBody = UserSignUpInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Budgets
	// (GET /budgets)
	GetBudgets(ctx echo.Context, params GetBudgetsParams) error
	// Create Budget
	// (POST /budgets)
	PostBudgets(ctx echo.Context) error
	// Delete Budget
	// (DELETE /budgets/{id})
	DeleteBudgetsId(ctx echo.Context, id int32) error
	// Get Budget
	// (GET /budgets/{id})
	GetBudgetsId(ctx echo.Context, id int32) error
	// Update Budget
	// (PATCH /budgets/{id})
	PatchBudgetsId(ctx echo.Context, id int32) error
	// Get Categories
	// (GET /categories)
	GetCategories(ctx echo.Context) error
	// Create Category
	// (POST /categories)
	PostCategories(ctx echo.Context) error
	// Delete Category
	// (DELETE /categories/{id})
	DeleteCategoriesId(ctx echo.Context, id int32) error
	// Get Category
	// (GET /categories/{id})
	GetCategoriesId(ctx echo.Context, id int32) error
	// Update Category
	// (PATCH /categories/{id})
	PatchCategoriesId(ctx echo.Context, id int32) error
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Get Transactions
	// (GET /transactions)
	GetTransactions(ctx echo.Context, params GetTransactionsParams) error
	// Create Transaction
	// (POST /transactions)
	PostTransactions(ctx echo.Context) error
	// Delete Transaction
	// (DELETE /transactions/{id})
	DeleteTransactionsId(ctx echo.Context, id int32) error
	// Get Transaction
	// (GET /transactions/{id})
	GetTransactionsId(ctx echo.Context, id int32) error
	// Update Transaction
	// (PATCH /transactions/{id})
	PatchTransactionsId(ctx echo.Context, id int32) error
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx echo.Context) error
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx echo.Context) error
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetBudgets converts echo context to params.
func (w *ServerInterfaceWrapper) GetBudgets(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBudgetsParams
	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameter("form", false, false, "month", ctx.QueryParams(), &params.Month)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", false, false, "category_id", ctx.QueryParams(), &params.CategoryId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBudgets(ctx, params)
	return err
}

// PostBudgets converts echo context to params.
func (w *ServerInterfaceWrapper) PostBudgets(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBudgets(ctx)
	return err
}

// DeleteBudgetsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBudgetsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBudgetsId(ctx, id)
	return err
}

// GetBudgetsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetBudgetsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBudgetsId(ctx, id)
	return err
}

// PatchBudgetsId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchBudgetsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchBudgetsId(ctx, id)
	return err
}

// GetCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategories(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategories(ctx)
	return err
}

// PostCategories converts echo context to params.
func (w *ServerInterfaceWrapper) PostCategories(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCategories(ctx)
	return err
}

// DeleteCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCategoriesId(ctx, id)
	return err
}

// GetCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategoriesId(ctx, id)
	return err
}

// PatchCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchCategoriesId(ctx, id)
	return err
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// GetTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsParams
	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", false, false, "start_date", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_date: %s", err))
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", false, false, "end_date", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_date: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", false, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", false, false, "category_id", ctx.QueryParams(), &params.CategoryId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransactions(ctx, params)
	return err
}

// PostTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) PostTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTransactions(ctx)
	return err
}

// DeleteTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTransactionsId(ctx, id)
	return err
}

// GetTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransactionsId(ctx, id)
	return err
}

// PatchTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTransactionsId(ctx, id)
	return err
}

// GetUsersCheckSignedIn converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersCheckSignedIn(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersCheckSignedIn(ctx)
	return err
}

// PostUsersSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignIn(ctx)
	return err
}

// PostUsersSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignUp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/budgets", wrapper.GetBudgets)
	router.POST(baseURL+"/budgets", wrapper.PostBudgets)
	router.DELETE(baseURL+"/budgets/:id", wrapper.DeleteBudgetsId)
	router.GET(baseURL+"/budgets/:id", wrapper.GetBudgetsId)
	router.PATCH(baseURL+"/budgets/:id", wrapper.PatchBudgetsId)
	router.GET(baseURL+"/categories", wrapper.GetCategories)
	router.POST(baseURL+"/categories", wrapper.PostCategories)
	router.DELETE(baseURL+"/categories/:id", wrapper.DeleteCategoriesId)
	router.GET(baseURL+"/categories/:id", wrapper.GetCategoriesId)
	router.PATCH(baseURL+"/categories/:id", wrapper.PatchCategoriesId)
	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.GET(baseURL+"/transactions", wrapper.GetTransactions)
	router.POST(baseURL+"/transactions", wrapper.PostTransactions)
	router.DELETE(baseURL+"/transactions/:id", wrapper.DeleteTransactionsId)
	router.GET(baseURL+"/transactions/:id", wrapper.GetTransactionsId)
	router.PATCH(baseURL+"/transactions/:id", wrapper.PatchTransactionsId)
	router.GET(baseURL+"/users/checkSignedIn", wrapper.GetUsersCheckSignedIn)
	router.POST(baseURL+"/users/signIn", wrapper.PostUsersSignIn)
	router.POST(baseURL+"/users/signUp", wrapper.PostUsersSignUp)

}

type GetBudgetsRequestObject struct {
	Params GetBudgetsParams
}

type GetBudgetsResponseObject interface {
	VisitGetBudgetsResponse(w http.ResponseWriter) error
}

type GetBudgets200JSONResponse FetchBudgetListResponse

func (response GetBudgets200JSONResponse) VisitGetBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgets400JSONResponse ErrorBody

func (response GetBudgets400JSONResponse) VisitGetBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgets500JSONResponse ErrorBody

func (response GetBudgets500JSONResponse) VisitGetBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgetsRequestObject struct {
	Body *PostBudgetsJSONRequestBody
}

type PostBudgetsResponseObject interface {
	VisitPostBudgetsResponse(w http.ResponseWriter) error
}

type PostBudgets201JSONResponse CreateBudgetResponse

func (response PostBudgets201JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgets400JSONResponse ErrorBody

func (response PostBudgets400JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgets409JSONResponse ErrorBody

func (response PostBudgets409JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgets500JSONResponse ErrorBody

func (response PostBudgets500JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteBudgetsIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteBudgetsIdResponseObject interface {
	VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error
}

type DeleteBudgetsId204Response struct {
}

func (response DeleteBudgetsId204Response) VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteBudgetsId404JSONResponse ErrorBody

func (response DeleteBudgetsId404JSONResponse) VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteBudgetsId500JSONResponse ErrorBody

func (response DeleteBudgetsId500JSONResponse) VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsIdRequestObject struct {
	Id int32 `json:"id"`
}

type GetBudgetsIdResponseObject interface {
	VisitGetBudgetsIdResponse(w http.ResponseWriter) error
}

type GetBudgetsId200JSONResponse FetchBudgetResponse

func (response GetBudgetsId200JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsId400JSONResponse ErrorBody

func (response GetBudgetsId400JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsId404JSONResponse ErrorBody

func (response GetBudgetsId404JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsId500JSONResponse ErrorBody

func (response GetBudgetsId500JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PatchBudgetsIdJSONRequestBody
}

type PatchBudgetsIdResponseObject interface {
	VisitPatchBudgetsIdResponse(w http.ResponseWriter) error
}

type PatchBudgetsId200JSONResponse UpdateBudgetResponse

func (response PatchBudgetsId200JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId400JSONResponse ErrorBody

func (response PatchBudgetsId400JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId404JSONResponse ErrorBody

func (response PatchBudgetsId404JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId409JSONResponse ErrorBody

func (response PatchBudgetsId409JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId500JSONResponse ErrorBody

func (response PatchBudgetsId500JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesRequestObject struct {
}

type GetCategoriesResponseObject interface {
	VisitGetCategoriesResponse(w http.ResponseWriter) error
}

type GetCategories200JSONResponse FetchCategoryListsResponse

func (response GetCategories200JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategories500JSONResponse ErrorBody

func (response GetCategories500JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostCategoriesRequestObject struct {
	Body *PostCategoriesJSONRequestBody
}

type PostCategoriesResponseObject interface {
	VisitPostCategoriesResponse(w http.ResponseWriter) error
}

type PostCategories201JSONResponse CreateCategoryResponse

func (response PostCategories201JSONResponse) VisitPostCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostCategories400JSONResponse ErrorBody

func (response PostCategories400JSONResponse) VisitPostCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostCategories500JSONResponse ErrorBody

func (response PostCategories500JSONResponse) VisitPostCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoriesIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteCategoriesIdResponseObject interface {
	VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error
}

type DeleteCategoriesId204Response struct {
}

func (response DeleteCategoriesId204Response) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCategoriesId400JSONResponse ErrorBody

func (response DeleteCategoriesId400JSONResponse) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoriesId404JSONResponse ErrorBody

func (response DeleteCategoriesId404JSONResponse) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoriesId500JSONResponse ErrorBody

func (response DeleteCategoriesId500JSONResponse) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesIdRequestObject struct {
	Id int32 `json:"id"`
}

type GetCategoriesIdResponseObject interface {
	VisitGetCategoriesIdResponse(w http.ResponseWriter) error
}

type GetCategoriesId200JSONResponse FetchCategoryResponse

func (response GetCategoriesId200JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesId400JSONResponse ErrorBody

func (response GetCategoriesId400JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesId404JSONResponse ErrorBody

func (response GetCategoriesId404JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesId500JSONResponse ErrorBody

func (response GetCategoriesId500JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PatchCategoriesIdJSONRequestBody
}

type PatchCategoriesIdResponseObject interface {
	VisitPatchCategoriesIdResponse(w http.ResponseWriter) error
}

type PatchCategoriesId200JSONResponse UpdateCategoryResponse

func (response PatchCategoriesId200JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesId400JSONResponse ErrorBody

func (response PatchCategoriesId400JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesId404JSONResponse ErrorBody

func (response PatchCategoriesId404JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesId500JSONResponse ErrorBody

func (response PatchCategoriesId500JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrfRequestObject struct {
}

type GetCsrfResponseObject interface {
	VisitGetCsrfResponse(w http.ResponseWriter) error
}

type GetCsrf200JSONResponse CsrfResponse

func (response GetCsrf200JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrf500JSONResponse ErrorBody

func (response GetCsrf500JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsRequestObject struct {
	Params GetTransactionsParams
}

type GetTransactionsResponseObject interface {
	VisitGetTransactionsResponse(w http.ResponseWriter) error
}

type GetTransactions200JSONResponse FetchTransactionListResponse

func (response GetTransactions200JSONResponse) VisitGetTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactions400JSONResponse ErrorBody

func (response GetTransactions400JSONResponse) VisitGetTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactions500JSONResponse ErrorBody

func (response GetTransactions500JSONResponse) VisitGetTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostTransactionsRequestObject struct {
	Body *PostTransactionsJSONRequestBody
}

type PostTransactionsResponseObject interface {
	VisitPostTransactionsResponse(w http.ResponseWriter) error
}

type PostTransactions201JSONResponse CreateTransactionResponse

func (response PostTransactions201JSONResponse) VisitPostTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostTransactions400JSONResponse ErrorBody

func (response PostTransactions400JSONResponse) VisitPostTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostTransactions500JSONResponse ErrorBody

func (response PostTransactions500JSONResponse) VisitPostTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTransactionsIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteTransactionsIdResponseObject interface {
	VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error
}

type DeleteTransactionsId204Response struct {
}

func (response DeleteTransactionsId204Response) VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTransactionsId404JSONResponse ErrorBody

func (response DeleteTransactionsId404JSONResponse) VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTransactionsId500JSONResponse ErrorBody

func (response DeleteTransactionsId500JSONResponse) VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsIdRequestObject struct {
	Id int32 `json:"id"`
}

type GetTransactionsIdResponseObject interface {
	VisitGetTransactionsIdResponse(w http.ResponseWriter) error
}

type GetTransactionsId200JSONResponse FetchTransactionResponse

func (response GetTransactionsId200JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsId400JSONResponse ErrorBody

func (response GetTransactionsId400JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsId404JSONResponse ErrorBody

func (response GetTransactionsId404JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsId500JSONResponse ErrorBody

func (response GetTransactionsId500JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PatchTransactionsIdJSONRequestBody
}

type PatchTransactionsIdResponseObject interface {
	VisitPatchTransactionsIdResponse(w http.ResponseWriter) error
}

type PatchTransactionsId200JSONResponse UpdateTransactionResponse

func (response PatchTransactionsId200JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsId400JSONResponse ErrorBody

func (response PatchTransactionsId400JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsId404JSONResponse ErrorBody

func (response PatchTransactionsId404JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsId500JSONResponse ErrorBody

func (response PatchTransactionsId500JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersCheckSignedInRequestObject struct {
}

type GetUsersCheckSignedInResponseObject interface {
	VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error
}

type GetUsersCheckSignedIn200JSONResponse UserUserCheckSignedInResponse

func (response GetUsersCheckSignedIn200JSONResponse) VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignInRequestObject struct {
	Body *PostUsersSignInJSONRequestBody
}

type PostUsersSignInResponseObject interface {
	VisitPostUsersSignInResponse(w http.ResponseWriter) error
}

type PostUsersSignIn200ResponseHeaders struct {
	SetCookie string
}

type PostUsersSignIn200JSONResponse struct {
	Body    UserUserSignInResponse
	Headers PostUsersSignIn200ResponseHeaders
}

func (response PostUsersSignIn200JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("set-cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostUsersSignIn400JSONResponse ErrorBody

func (response PostUsersSignIn400JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignIn401JSONResponse ErrorBody

func (response PostUsersSignIn401JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignIn500JSONResponse ErrorBody

func (response PostUsersSignIn500JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUpRequestObject struct {
	Body *PostUsersSignUpJSONRequestBody
}

type PostUsersSignUpResponseObject interface {
	VisitPostUsersSignUpResponse(w http.ResponseWriter) error
}

type PostUsersSignUp200JSONResponse UserUserSignUpResponse

func (response PostUsersSignUp200JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp400JSONResponse ErrorBody

func (response PostUsersSignUp400JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp409JSONResponse ErrorBody

func (response PostUsersSignUp409JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp500JSONResponse ErrorBody

func (response PostUsersSignUp500JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Budgets
	// (GET /budgets)
	GetBudgets(ctx context.Context, request GetBudgetsRequestObject) (GetBudgetsResponseObject, error)
	// Create Budget
	// (POST /budgets)
	PostBudgets(ctx context.Context, request PostBudgetsRequestObject) (PostBudgetsResponseObject, error)
	// Delete Budget
	// (DELETE /budgets/{id})
	DeleteBudgetsId(ctx context.Context, request DeleteBudgetsIdRequestObject) (DeleteBudgetsIdResponseObject, error)
	// Get Budget
	// (GET /budgets/{id})
	GetBudgetsId(ctx context.Context, request GetBudgetsIdRequestObject) (GetBudgetsIdResponseObject, error)
	// Update Budget
	// (PATCH /budgets/{id})
	PatchBudgetsId(ctx context.Context, request PatchBudgetsIdRequestObject) (PatchBudgetsIdResponseObject, error)
	// Get Categories
	// (GET /categories)
	GetCategories(ctx context.Context, request GetCategoriesRequestObject) (GetCategoriesResponseObject, error)
	// Create Category
	// (POST /categories)
	PostCategories(ctx context.Context, request PostCategoriesRequestObject) (PostCategoriesResponseObject, error)
	// Delete Category
	// (DELETE /categories/{id})
	DeleteCategoriesId(ctx context.Context, request DeleteCategoriesIdRequestObject) (DeleteCategoriesIdResponseObject, error)
	// Get Category
	// (GET /categories/{id})
	GetCategoriesId(ctx context.Context, request GetCategoriesIdRequestObject) (GetCategoriesIdResponseObject, error)
	// Update Category
	// (PATCH /categories/{id})
	PatchCategoriesId(ctx context.Context, request PatchCategoriesIdRequestObject) (PatchCategoriesIdResponseObject, error)
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx context.Context, request GetCsrfRequestObject) (GetCsrfResponseObject, error)
	// Get Transactions
	// (GET /transactions)
	GetTransactions(ctx context.Context, request GetTransactionsRequestObject) (GetTransactionsResponseObject, error)
	// Create Transaction
	// (POST /transactions)
	PostTransactions(ctx context.Context, request PostTransactionsRequestObject) (PostTransactionsResponseObject, error)
	// Delete Transaction
	// (DELETE /transactions/{id})
	DeleteTransactionsId(ctx context.Context, request DeleteTransactionsIdRequestObject) (DeleteTransactionsIdResponseObject, error)
	// Get Transaction
	// (GET /transactions/{id})
	GetTransactionsId(ctx context.Context, request GetTransactionsIdRequestObject) (GetTransactionsIdResponseObject, error)
	// Update Transaction
	// (PATCH /transactions/{id})
	PatchTransactionsId(ctx context.Context, request PatchTransactionsIdRequestObject) (PatchTransactionsIdResponseObject, error)
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx context.Context, request GetUsersCheckSignedInRequestObject) (GetUsersCheckSignedInResponseObject, error)
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx context.Context, request PostUsersSignInRequestObject) (PostUsersSignInResponseObject, error)
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx context.Context, request PostUsersSignUpRequestObject) (PostUsersSignUpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetBudgets operation middleware
func (sh *strictHandler) GetBudgets(ctx echo.Context, params GetBudgetsParams) error {
	var request GetBudgetsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBudgets(ctx.Request().Context(), request.(GetBudgetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBudgets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBudgetsResponseObject); ok {
		return validResponse.VisitGetBudgetsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostBudgets operation middleware
func (sh *strictHandler) PostBudgets(ctx echo.Context) error {
	var request PostBudgetsRequestObject

	var body PostBudgetsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostBudgets(ctx.Request().Context(), request.(PostBudgetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostBudgets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostBudgetsResponseObject); ok {
		return validResponse.VisitPostBudgetsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBudgetsId operation middleware
func (sh *strictHandler) DeleteBudgetsId(ctx echo.Context, id int32) error {
	var request DeleteBudgetsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBudgetsId(ctx.Request().Context(), request.(DeleteBudgetsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBudgetsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteBudgetsIdResponseObject); ok {
		return validResponse.VisitDeleteBudgetsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBudgetsId operation middleware
func (sh *strictHandler) GetBudgetsId(ctx echo.Context, id int32) error {
	var request GetBudgetsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBudgetsId(ctx.Request().Context(), request.(GetBudgetsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBudgetsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBudgetsIdResponseObject); ok {
		return validResponse.VisitGetBudgetsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchBudgetsId operation middleware
func (sh *strictHandler) PatchBudgetsId(ctx echo.Context, id int32) error {
	var request PatchBudgetsIdRequestObject

	request.Id = id

	var body PatchBudgetsIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchBudgetsId(ctx.Request().Context(), request.(PatchBudgetsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchBudgetsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchBudgetsIdResponseObject); ok {
		return validResponse.VisitPatchBudgetsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategories operation middleware
func (sh *strictHandler) GetCategories(ctx echo.Context) error {
	var request GetCategoriesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategories(ctx.Request().Context(), request.(GetCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesResponseObject); ok {
		return validResponse.VisitGetCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostCategories operation middleware
func (sh *strictHandler) PostCategories(ctx echo.Context) error {
	var request PostCategoriesRequestObject

	var body PostCategoriesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCategories(ctx.Request().Context(), request.(PostCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCategoriesResponseObject); ok {
		return validResponse.VisitPostCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteCategoriesId operation middleware
func (sh *strictHandler) DeleteCategoriesId(ctx echo.Context, id int32) error {
	var request DeleteCategoriesIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCategoriesId(ctx.Request().Context(), request.(DeleteCategoriesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCategoriesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCategoriesIdResponseObject); ok {
		return validResponse.VisitDeleteCategoriesIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategoriesId operation middleware
func (sh *strictHandler) GetCategoriesId(ctx echo.Context, id int32) error {
	var request GetCategoriesIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategoriesId(ctx.Request().Context(), request.(GetCategoriesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategoriesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesIdResponseObject); ok {
		return validResponse.VisitGetCategoriesIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchCategoriesId operation middleware
func (sh *strictHandler) PatchCategoriesId(ctx echo.Context, id int32) error {
	var request PatchCategoriesIdRequestObject

	request.Id = id

	var body PatchCategoriesIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchCategoriesId(ctx.Request().Context(), request.(PatchCategoriesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchCategoriesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchCategoriesIdResponseObject); ok {
		return validResponse.VisitPatchCategoriesIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCsrf operation middleware
func (sh *strictHandler) GetCsrf(ctx echo.Context) error {
	var request GetCsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCsrf(ctx.Request().Context(), request.(GetCsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCsrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCsrfResponseObject); ok {
		return validResponse.VisitGetCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransactions operation middleware
func (sh *strictHandler) GetTransactions(ctx echo.Context, params GetTransactionsParams) error {
	var request GetTransactionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactions(ctx.Request().Context(), request.(GetTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTransactionsResponseObject); ok {
		return validResponse.VisitGetTransactionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostTransactions operation middleware
func (sh *strictHandler) PostTransactions(ctx echo.Context) error {
	var request PostTransactionsRequestObject

	var body PostTransactionsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostTransactions(ctx.Request().Context(), request.(PostTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTransactions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostTransactionsResponseObject); ok {
		return validResponse.VisitPostTransactionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTransactionsId operation middleware
func (sh *strictHandler) DeleteTransactionsId(ctx echo.Context, id int32) error {
	var request DeleteTransactionsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTransactionsId(ctx.Request().Context(), request.(DeleteTransactionsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTransactionsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTransactionsIdResponseObject); ok {
		return validResponse.VisitDeleteTransactionsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransactionsId operation middleware
func (sh *strictHandler) GetTransactionsId(ctx echo.Context, id int32) error {
	var request GetTransactionsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactionsId(ctx.Request().Context(), request.(GetTransactionsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactionsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTransactionsIdResponseObject); ok {
		return validResponse.VisitGetTransactionsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchTransactionsId operation middleware
func (sh *strictHandler) PatchTransactionsId(ctx echo.Context, id int32) error {
	var request PatchTransactionsIdRequestObject

	request.Id = id

	var body PatchTransactionsIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchTransactionsId(ctx.Request().Context(), request.(PatchTransactionsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchTransactionsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchTransactionsIdResponseObject); ok {
		return validResponse.VisitPatchTransactionsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUsersCheckSignedIn operation middleware
func (sh *strictHandler) GetUsersCheckSignedIn(ctx echo.Context) error {
	var request GetUsersCheckSignedInRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersCheckSignedIn(ctx.Request().Context(), request.(GetUsersCheckSignedInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersCheckSignedIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersCheckSignedInResponseObject); ok {
		return validResponse.VisitGetUsersCheckSignedInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignIn operation middleware
func (sh *strictHandler) PostUsersSignIn(ctx echo.Context) error {
	var request PostUsersSignInRequestObject

	var body PostUsersSignInJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignIn(ctx.Request().Context(), request.(PostUsersSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignInResponseObject); ok {
		return validResponse.VisitPostUsersSignInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignUp operation middleware
func (sh *strictHandler) PostUsersSignUp(ctx echo.Context) error {
	var request PostUsersSignUpRequestObject

	var body PostUsersSignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignUp(ctx.Request().Context(), request.(PostUsersSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignUpResponseObject); ok {
		return validResponse.VisitPostUsersSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcb3PbRBr/KhrdvaAzbuJCOwd+hZuY4iFxMv5zXKaTyWytTSywJaOVgVwnM9g+Skoo",
	"DRwk9I47KBBaUpoWWjgupPTDqHacV/kKN7sryStp9cclTnyJ32Rie7X77LPP77fP/nZXl8WiWqmqClR0",
	"JCYui6hYghVA/j1fkxagjv+TICpqclWXVUVMWN/HxKqmVqGmy5AUBxW1pnCKP9le3t1a37t5TYyJ86pW",
	"AbqYEGVFf+5ZMSbqi1VIP8IFqIlLMbEIdLigaoukynJ5al5MXLws/lGD82JC/MNo19pR09TRMeuJpdmY",
	"q22jccdoXjEaD43mZrv5buvLH9gm5mTJay77SHo8os0aBDqU5gCv+48+by+vttc32jcabG0S0OFpXa7A",
	"bo1I12RlAVfIM4z6MapJFVXRS95KWvd+6/xws/358v7O8szMzMzpycnWo69aO9f3d66KMbEC3p6AygJ+",
	"8k8xsSIrzCePkbWq5Nvr9j8fttfu99jrGoIaf0ya3xrNHaPxs9HcieaApZiowTdqsgYlMXER+7NbvTMA",
	"mIiLWTFsuc8xso4Oz9pNqpdeg0Udmz/GRK7T/rFuC07MFNWyqgXHoFHf6lz90Tk2z8Y53juUIHwadCig",
	"AoNraq1ec3bwTDx+rAKOuCBmDnePUUXKUs5NK9Uap++0iEDLCLTQgbBzRVbkSq0iJs4EMfWB0WjfOcs1",
	"SE4acGE/bCyyEFVVBcGw4bDLuUfkkj29Bk1u5mTrNt182N9Ii3KCQ8Yq5RM0B0lPB8QCLj84gBXujdBB",
	"sx3iO2xsfhItK/GJugBz8xpQEChi04LHjynYI+733vtoMECPyY+D+etrrZ1P2+sbbi7n0bjjUXdNnc3v",
	"25996ArQc+c41dAvomadjOvz+EFv8kn7YDQeG41vjOb6/s5y6/qHrXc3Rtuf3Gu9t43ZK5iRiEEMMZH+",
	"R4qa0DhnA8c31PVuobBoZ+rzdIqthms90uZZg114Q9p8Xn0dEhNC+NwuipuR9TIu66id03pK01TtvCot",
	"8sL5ttH8DicCze+Nxn+N5r+M5gPyz+dG8z2j8bXHYxBXFuYr0qJtkrsTtIpZP0vTyrwaYGnnuwe7D++b",
	"Sx23dS9aEe6K03+vdO5+1lreaN1dFWMiVDD4LzLNzfIwp1aArAT5rP7B7o3t3U++MOrrRv0Lo3nVaN4k",
	"SHjAw3AF6kACOiAAlCQZVwfK0854DAS+2Hn8qPX+l0Z9izT0GA8RzuEe7+8sG427ZBh/NZqreNJqbhjN",
	"HZo+eNysQYBowEcjAnM4yUO8Fajtj63d1Su7n/zgGfEXTZybDdu+9Y2BrG2hT1u0IaO+1dr6R/vT++yg",
	"TibTE3PJiWwqOT4zl/pLOpfPiTExnflzciI9Pkd+Zj5PJ3O5V6eymMoLuVR2LjOVn3tpqpAZZ8qMZVPj",
	"qUw+nZzANY0l86kLU9kZR1H7y3RmrpBLsQ/bxZOT3O/HpiamsmJMzGeTmVxyLJ+eynCtYH/Pz0yzdSUn",
	"pwqZPPPFeDKPfz9fGL+QynNrm5zK5F9mPptF7Zqsz24/jifzyfPJXGoulc0SswuZVzJTr2bMzzwgOdkg",
	"MgdxcjWJ8/jL+fw0eewKxQL+v/GAVHc14vwMdSCXEWdiJVRj1DdtE23akXVYQZFokPCLPfeKQNPAIqUD",
	"hMAC5K1XtvfW/m7UP+hs3jUadaOxwnjoptFsGo1fSVd/4bEM0oFeQz1iO0cf8mK7fftGe3ut277Tz97p",
	"CY9Qt2u2Nb44z9nW9tLu/s7yBVVdKEMhOZ0WcjpQJKBJ7e219sqXlPIsMrABkr1QmEyRwPZENIuO6VR2",
	"Mp3LYYiNpzLpFKGFTLKQfxnjH0OWYiifymaSE9xofwnqxRJd00zIKGARRQpaayhcNGwhRf6NFHjWksod",
	"ddwlFn94mG5E7MKhLwNJ69YiBDsQhVlqr31I6dAVkPkpksu7i6EQpzN1h3Yqcn+OaC1HrGAS4ygBz+bl",
	"wVHPZNXRx8GRpocMhaOBKP3rpW9HvebIO5txmsv++PvX08MtDv6ifWDW/TwXUTuiOucolINjuf/CVTyc",
	"3ulNPXf72megbVcz2ZGsFFXiJ/h2FWKq4uUzBdJ8oDpPizjUeeGZKtB0GZQFav6poVzvI9d7BpR1uP+E",
	"4/T5oedetPkQCd600SnBh0fGYGryIS4IHamjztWoGeG6u2muR3d/ekQPhfhBEeLDgyI0jAcpxS0gqI3k",
	"5AUl7RfM+Ech7bdzBCtALvNygZtEa7ljNL4iou73VI3yjGIVIPSWqnHTiY+IZnHP1qGCdX1qCVNjYHcL",
	"1aDuFqp96q4PlzKZE+XSPvrJ3AyN7i78Z6wEi69j10ApHRTgCGqCo6x/gMtoDpFCc9wdguZdo3Gf7gTs",
	"vv9z+92VbscuqWoZAm+sO2oM7A4N+JB+WIEftC/kqLFQjVJjoervE19BM1S1dLnCqsjrhaWYiGCxpsn6",
	"Yg7zB204WZVfgYvJGk3V8ICIRVV9XYbWsZSEqJM9s64cQJ4Ql3CFMne7ycyrxkAZKhLQhOR0WuzuuLl/",
	"zUHtTbmI23sTaojWcGYkjp2sVqECqrKYEJ8biY/ESdDqJWL3KCPrcY8hstAy6nd2H64a9Q2jfp2myE9+",
	"eafz7S2j8TEm/9/WjXcaRuMekUw3Maya35nAbjw26reM5qdG42sC8sekwAOjcb91/V6n+UgkRmqA5ASS",
	"mBAvQP28aRm2VgMVqEMNkWmqp0QYvl0tE81+HpQRjNGheaMGyULIHBnrGBqdD7g7oKFTf5R2nAuybmvh",
	"67xZHJ005slQPRuP0yxV0SFNd0C1WpaLxIGjr5n7Vt0WgmY/P7GYRKZLsilBAaMEIl0oASSgWrEIoQSl",
	"ERxmZw/QqO5+MceMs/G4cB5IQtY05bRgbTjSvcj/GM1bJLpM6V545slvKwnBsf0WE9y7b6dwH84dVh/O",
	"xeNCWtGhpoAywS7UBPIA7k3jJzIXrZLeODvh3PuKCY6tr1MOeiJgYYnp4iwOJFSrVADO8DHIhC7KdLCA",
	"HIo8njVVxJM91u6T7ea/URIwGh9TbcqD4mkVMTA2I8c6BXAgPvae21tyUrmu1eCSBz1n+mLAU0FHAIok",
	"AEGBbwkaRGpNK0JS4BKEimCKMAJAAsA/18r6sYHa2fgLh9WHF4QxVZkvy0XagU2j8Yju6O3e+bm1uuy2",
	"nrd9f/LYwXHAkssPSzE7fxi9LEtLlCnKUId+khrOFK6+v3fjGw9VjJPnTLJIS2GzPnNMn8y0OKHpTrRk",
	"fnVywO+db89yNjBKUIOCjARFFcyQEHRVQFCRhHlVE/SSjCzMx4RLNV3QS1AoQSBBDQkVsChcgkINwfla",
	"eUSgiDh7OOGFyQjRqCoCRVF1YV5WJGKeaS+UbDYaOXGRT2MxKPJj/GTZDPL6lnlqw8qLA9LbAQz1vqSW",
	"JzutHCJ70DJev4QX6MVSwOxFd/z2d5b3mrdby1esj1e9qS+wQ39AMH7wybd3Wy5S8h3viwFDghlQghnm",
	"+YPNiY5dXN8833kcrSepkNXKXIIhLzEa67bU79SEf3CvZwI5cVOoY4iseGEPFYZLR46d9EAByRUP/dKQ",
	"nOcIjkRF8uzjD3WkoWTLFWWYq+5c+DkZO1SccYExUKLpwjE8rfXskhwnrWaYNA5XpQeqN4WB2kd0cp9J",
	"C5ee/g8g3KdEb7hIHOJ9oFLoALD7SFGuubo3QWowkd8vZeopUvp4n0wYEs+QeAZG6om0ekDavK/SM5bL",
	"vmQ0l4m190hMmNnG/s5yZ/Na5/bOk1+udb6t83gI5x+47j5Cz/EyipOp5jjnGupve6zxRzrK7uuNPel6",
	"9MB3P48A5lnzQqarvbWV1q2V9vpG9xzg6fHxXo8CIh1o+px58p4zkfHP5HvPB+7+1HiyfeX3WgMV6QBs",
	"8R7Mp5euRs0rV9HtMS+ORYt9z42B43+K0u8a8vAo5UlI6V1sZdGt84Z3uDJuwTVIE3c11T9V3HNX60iE",
	"cd7loKE2PsQgVxt3vlfAB4Xu5CdUIrdRGSiOs7gMX2Ez19+HhxiHa72+iMqR0OCjLJsxH0lTHvDI71+i",
	"N1R2hmgfuPwzMP3k68r2BNebojx4uO+Xmvx0qXC8f1YMmWfIPAOjKUfOumsIami0yN5xD1Ae3ZfYd7/a",
	"7mxe4yUgBVyv4+p8PyXmkIv9PSKyJ397XhHA+Js41+FoRG7qkxc+c2UHh7jLuJsrOxAf07v/fVIdPK/T",
	"OGyS9XnDQW8DGhPNBRJpGOqnzXcBOMxw67ZLx4aYzxxWH84IBQXU9JKqyX+FknBaoJtPflYz71A+dfx2",
	"euw3ZERghEI1GiPs3vh174Mfg7mgUO03F1jvmjlKLmDeTXJC063hLY7BgDfBmwfeJIXALdNlV00riwmx",
	"pOvVxOhoWS2CcklFeuL5+PNx8uou8/nL9qYa0ubFpdhl1yabDBH7LW2N+cKR3zHfW3dHlmaX/hcAAP//",
	"+oyvhPtuAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
