// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ErrorInfoType.
const (
	ErrorInfoTypeErrorInfo ErrorInfoType = "ErrorInfo"
)

// Defines values for ErrorReason.
const (
	BUDGETALREADYEXISTS    ErrorReason = "BUDGET_ALREADY_EXISTS"
	BUDGETNOTFOUND         ErrorReason = "BUDGET_NOT_FOUND"
	CATEGORYINUSE          ErrorReason = "CATEGORY_IN_USE"
	CATEGORYNOTFOUND       ErrorReason = "CATEGORY_NOT_FOUND"
	DATABASEERROR          ErrorReason = "DATABASE_ERROR"
	EMAILALREADYEXISTS     ErrorReason = "EMAIL_ALREADY_EXISTS"
	INVALIDAMOUNT          ErrorReason = "INVALID_AMOUNT"
	INVALIDBUDGETAMOUNT    ErrorReason = "INVALID_BUDGET_AMOUNT"
	INVALIDCATEGORYCOLOR   ErrorReason = "INVALID_CATEGORY_COLOR"
	INVALIDCATEGORYNAME    ErrorReason = "INVALID_CATEGORY_NAME"
	INVALIDCREDENTIALS     ErrorReason = "INVALID_CREDENTIALS"
	INVALIDDATE            ErrorReason = "INVALID_DATE"
	INVALIDEMAIL           ErrorReason = "INVALID_EMAIL"
	INVALIDMONTH           ErrorReason = "INVALID_MONTH"
	INVALIDPASSWORD        ErrorReason = "INVALID_PASSWORD"
	INVALIDTRANSACTIONTYPE ErrorReason = "INVALID_TRANSACTION_TYPE"
	TRANSACTIONNOTFOUND    ErrorReason = "TRANSACTION_NOT_FOUND"
	UNKNOWNERROR           ErrorReason = "UNKNOWN_ERROR"
	USERNOTFOUND           ErrorReason = "USER_NOT_FOUND"
	VALIDATIONERROR        ErrorReason = "VALIDATION_ERROR"
)

// Defines values for ErrorStatus.
const (
	ALREADYEXISTS    ErrorStatus = "ALREADY_EXISTS"
	INTERNAL         ErrorStatus = "INTERNAL"
	INVALIDARGUMENT  ErrorStatus = "INVALID_ARGUMENT"
	NOTFOUND         ErrorStatus = "NOT_FOUND"
	PERMISSIONDENIED ErrorStatus = "PERMISSION_DENIED"
	UNAUTHENTICATED  ErrorStatus = "UNAUTHENTICATED"
)

// Defines values for TransactionType.
const (
	Expense TransactionType = "expense"
	Income  TransactionType = "income"
)

// Budget Budget
type Budget struct {
	// Amount 予算額
	Amount int32 `json:"amount"`

	// Category カテゴリ情報
	Category Category `json:"category"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Id 予算ID
	Id int32 `json:"id"`

	// Month 対象月（YYYY-MM形式）
	Month string `json:"month"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// Category Category
type Category struct {
	// Color カテゴリの色
	Color string `json:"color"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Id カテゴリID
	Id int32 `json:"id"`

	// Name カテゴリ名
	Name string `json:"name"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// CreateBudgetInput Create Budget Input
type CreateBudgetInput struct {
	// Amount 予算額
	Amount int32 `json:"amount"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// Month 対象月（YYYY-MM形式）
	Month string `json:"month"`
}

// CreateBudgetResponse Create Budget Response
type CreateBudgetResponse struct {
	// Budget Budget
	Budget Budget `json:"budget"`
}

// CreateCategoryInput Create Category Input
type CreateCategoryInput struct {
	// Color カテゴリの色
	Color string `json:"color"`

	// Name カテゴリ名
	Name string `json:"name"`
}

// CreateCategoryResponse Create Category Response
type CreateCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// CreateTransactionInput Create Transaction Input
type CreateTransactionInput struct {
	// Amount 金額
	Amount int32 `json:"amount"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// Date 取引日
	Date openapi_types.Date `json:"date"`

	// Description 説明
	Description *string `json:"description,omitempty"`

	// Type 取引タイプ（収入/支出）
	Type TransactionType `json:"type"`
}

// CreateTransactionResponse Create Transaction Response
type CreateTransactionResponse struct {
	// Transaction Transaction
	Transaction Transaction `json:"transaction"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// ErrorBody エラーレスポンスボディ
type ErrorBody struct {
	// Error エラーレスポンス
	Error ErrorResponse `json:"error"`
}

// ErrorInfo エラー詳細情報
type ErrorInfo struct {
	// Type 型識別子
	Type ErrorInfoType `json:"@type"`

	// Domain エラーが発生したドメイン
	Domain string `json:"domain"`

	// Metadata 追加のメタデータ（キー・バリュー）
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Reason エラーの理由
	Reason ErrorReason `json:"reason"`
}

// ErrorInfoType 型識別子
type ErrorInfoType string

// ErrorReason エラー理由の定数
type ErrorReason string

// ErrorResponse エラーレスポンス
type ErrorResponse struct {
	// Code HTTPステータスコード
	Code int32 `json:"code"`

	// Details 詳細なエラー情報
	Details *[]ErrorInfo `json:"details,omitempty"`

	// Message 人間が読めるエラーメッセージ
	Message string `json:"message"`

	// Status 標準エラーステータス
	Status ErrorStatus `json:"status"`
}

// ErrorStatus 標準エラーステータス（Google API Standard準拠）
type ErrorStatus string

// FetchBudgetListResponse Fetch Budget List Response
type FetchBudgetListResponse struct {
	Budgets []Budget `json:"budgets"`
}

// FetchBudgetResponse Fetch Budget Response
type FetchBudgetResponse struct {
	// Budget Budget
	Budget Budget `json:"budget"`
}

// FetchCategoryListsResponse Fetch Category Lists Response
type FetchCategoryListsResponse struct {
	Categories []Category `json:"categories"`
}

// FetchCategoryResponse Fetch Category Response
type FetchCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// FetchTransactionListResponse Fetch Transaction List Response
type FetchTransactionListResponse struct {
	Transactions []Transaction `json:"transactions"`
}

// FetchTransactionResponse Fetch Transaction Response
type FetchTransactionResponse struct {
	// Transaction Transaction
	Transaction Transaction `json:"transaction"`
}

// Transaction Transaction
type Transaction struct {
	// Amount 金額
	Amount int32 `json:"amount"`

	// Category カテゴリ情報
	Category Category `json:"category"`

	// CategoryId カテゴリID
	CategoryId int32 `json:"category_id"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Date 取引日
	Date openapi_types.Date `json:"date"`

	// Description 説明
	Description string `json:"description"`

	// Id 取引ID
	Id int32 `json:"id"`

	// Type 取引タイプ（収入/支出）
	Type TransactionType `json:"type"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// TransactionType 取引タイプ
type TransactionType string

// UpdateBudgetInput Update Budget Input (partial update)
type UpdateBudgetInput struct {
	// Amount 予算額
	Amount *int32 `json:"amount,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `json:"category_id,omitempty"`

	// Month 対象月（YYYY-MM形式）
	Month *string `json:"month,omitempty"`
}

// UpdateBudgetResponse Update Budget Response
type UpdateBudgetResponse struct {
	// Budget Budget
	Budget Budget `json:"budget"`
}

// UpdateCategoryInput Update Category Input (partial update)
type UpdateCategoryInput struct {
	// Color カテゴリの色
	Color *string `json:"color,omitempty"`

	// Name カテゴリ名
	Name *string `json:"name,omitempty"`
}

// UpdateCategoryResponse Update Category Response
type UpdateCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// UpdateTransactionInput Update Transaction Input (partial update)
type UpdateTransactionInput struct {
	// Amount 金額
	Amount *int32 `json:"amount,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `json:"category_id,omitempty"`

	// Date 取引日
	Date *openapi_types.Date `json:"date,omitempty"`

	// Description 説明
	Description *string `json:"description,omitempty"`

	// Type 取引タイプ（収入/支出）
	Type *TransactionType `json:"type,omitempty"`
}

// UpdateTransactionResponse Update Transaction Response
type UpdateTransactionResponse struct {
	// Transaction Transaction
	Transaction Transaction `json:"transaction"`
}

// UserSignInInput Sign In Input
type UserSignInInput struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Password パスワード
	Password string `json:"password"`
}

// UserSignUpInput Sign Up Input
type UserSignUpInput struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Name ユーザー名
	Name string `json:"name"`

	// Password パスワード
	Password string `json:"password"`
}

// UserUserCheckSignedInResponse User CheckSignedIn Response
type UserUserCheckSignedInResponse struct {
	// IsSignedIn ログイン状態
	IsSignedIn bool `json:"is_signed_in"`
}

// UserUserSignInResponse User Sign In Response
type UserUserSignInResponse = map[string]interface{}

// UserUserSignUpResponse User Sign Up Response
type UserUserSignUpResponse struct {
	// Message メッセージ
	Message string `json:"message"`
}

// GetBudgetsParams defines parameters for GetBudgets.
type GetBudgetsParams struct {
	// Month 対象月（YYYY-MM形式）
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// GetTransactionsParams defines parameters for GetTransactions.
type GetTransactionsParams struct {
	// StartDate 開始日（YYYY-MM-DD形式）
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate 終了日（YYYY-MM-DD形式）
	EndDate *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`

	// Type 取引タイプ（income/expense）
	Type *TransactionType `form:"type,omitempty" json:"type,omitempty"`

	// CategoryId カテゴリID
	CategoryId *int32 `form:"category_id,omitempty" json:"category_id,omitempty"`
}

// PostBudgetsJSONRequestBody defines body for PostBudgets for application/json ContentType.
type PostBudgetsJSONRequestBody = CreateBudgetInput

// PatchBudgetsIdJSONRequestBody defines body for PatchBudgetsId for application/json ContentType.
type PatchBudgetsIdJSONRequestBody = UpdateBudgetInput

// PostCategoriesJSONRequestBody defines body for PostCategories for application/json ContentType.
type PostCategoriesJSONRequestBody = CreateCategoryInput

// PatchCategoriesIdJSONRequestBody defines body for PatchCategoriesId for application/json ContentType.
type PatchCategoriesIdJSONRequestBody = UpdateCategoryInput

// PostTransactionsJSONRequestBody defines body for PostTransactions for application/json ContentType.
type PostTransactionsJSONRequestBody = CreateTransactionInput

// PatchTransactionsIdJSONRequestBody defines body for PatchTransactionsId for application/json ContentType.
type PatchTransactionsIdJSONRequestBody = UpdateTransactionInput

// PostUsersSignInJSONRequestBody defines body for PostUsersSignIn for application/json ContentType.
type PostUsersSignInJSONRequestBody = UserSignInInput

// PostUsersSignUpJSONRequestBody defines body for PostUsersSignUp for application/json ContentType.
type PostUsersSignUpJSONRequestBody = UserSignUpInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Budgets
	// (GET /budgets)
	GetBudgets(ctx echo.Context, params GetBudgetsParams) error
	// Create Budget
	// (POST /budgets)
	PostBudgets(ctx echo.Context) error
	// Delete Budget
	// (DELETE /budgets/{id})
	DeleteBudgetsId(ctx echo.Context, id int32) error
	// Get Budget
	// (GET /budgets/{id})
	GetBudgetsId(ctx echo.Context, id int32) error
	// Update Budget
	// (PATCH /budgets/{id})
	PatchBudgetsId(ctx echo.Context, id int32) error
	// Get Categories
	// (GET /categories)
	GetCategories(ctx echo.Context) error
	// Create Category
	// (POST /categories)
	PostCategories(ctx echo.Context) error
	// Delete Category
	// (DELETE /categories/{id})
	DeleteCategoriesId(ctx echo.Context, id int32) error
	// Get Category
	// (GET /categories/{id})
	GetCategoriesId(ctx echo.Context, id int32) error
	// Update Category
	// (PATCH /categories/{id})
	PatchCategoriesId(ctx echo.Context, id int32) error
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Get Transactions
	// (GET /transactions)
	GetTransactions(ctx echo.Context, params GetTransactionsParams) error
	// Create Transaction
	// (POST /transactions)
	PostTransactions(ctx echo.Context) error
	// Delete Transaction
	// (DELETE /transactions/{id})
	DeleteTransactionsId(ctx echo.Context, id int32) error
	// Get Transaction
	// (GET /transactions/{id})
	GetTransactionsId(ctx echo.Context, id int32) error
	// Update Transaction
	// (PATCH /transactions/{id})
	PatchTransactionsId(ctx echo.Context, id int32) error
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx echo.Context) error
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx echo.Context) error
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetBudgets converts echo context to params.
func (w *ServerInterfaceWrapper) GetBudgets(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBudgetsParams
	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameter("form", false, false, "month", ctx.QueryParams(), &params.Month)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", false, false, "category_id", ctx.QueryParams(), &params.CategoryId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBudgets(ctx, params)
	return err
}

// PostBudgets converts echo context to params.
func (w *ServerInterfaceWrapper) PostBudgets(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBudgets(ctx)
	return err
}

// DeleteBudgetsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBudgetsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBudgetsId(ctx, id)
	return err
}

// GetBudgetsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetBudgetsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBudgetsId(ctx, id)
	return err
}

// PatchBudgetsId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchBudgetsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchBudgetsId(ctx, id)
	return err
}

// GetCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategories(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategories(ctx)
	return err
}

// PostCategories converts echo context to params.
func (w *ServerInterfaceWrapper) PostCategories(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCategories(ctx)
	return err
}

// DeleteCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCategoriesId(ctx, id)
	return err
}

// GetCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategoriesId(ctx, id)
	return err
}

// PatchCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchCategoriesId(ctx, id)
	return err
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// GetTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsParams
	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", false, false, "start_date", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_date: %s", err))
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", false, false, "end_date", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_date: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", false, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", false, false, "category_id", ctx.QueryParams(), &params.CategoryId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransactions(ctx, params)
	return err
}

// PostTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) PostTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTransactions(ctx)
	return err
}

// DeleteTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTransactionsId(ctx, id)
	return err
}

// GetTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransactionsId(ctx, id)
	return err
}

// PatchTransactionsId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTransactionsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTransactionsId(ctx, id)
	return err
}

// GetUsersCheckSignedIn converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersCheckSignedIn(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersCheckSignedIn(ctx)
	return err
}

// PostUsersSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignIn(ctx)
	return err
}

// PostUsersSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignUp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/budgets", wrapper.GetBudgets)
	router.POST(baseURL+"/budgets", wrapper.PostBudgets)
	router.DELETE(baseURL+"/budgets/:id", wrapper.DeleteBudgetsId)
	router.GET(baseURL+"/budgets/:id", wrapper.GetBudgetsId)
	router.PATCH(baseURL+"/budgets/:id", wrapper.PatchBudgetsId)
	router.GET(baseURL+"/categories", wrapper.GetCategories)
	router.POST(baseURL+"/categories", wrapper.PostCategories)
	router.DELETE(baseURL+"/categories/:id", wrapper.DeleteCategoriesId)
	router.GET(baseURL+"/categories/:id", wrapper.GetCategoriesId)
	router.PATCH(baseURL+"/categories/:id", wrapper.PatchCategoriesId)
	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.GET(baseURL+"/transactions", wrapper.GetTransactions)
	router.POST(baseURL+"/transactions", wrapper.PostTransactions)
	router.DELETE(baseURL+"/transactions/:id", wrapper.DeleteTransactionsId)
	router.GET(baseURL+"/transactions/:id", wrapper.GetTransactionsId)
	router.PATCH(baseURL+"/transactions/:id", wrapper.PatchTransactionsId)
	router.GET(baseURL+"/users/checkSignedIn", wrapper.GetUsersCheckSignedIn)
	router.POST(baseURL+"/users/signIn", wrapper.PostUsersSignIn)
	router.POST(baseURL+"/users/signUp", wrapper.PostUsersSignUp)

}

type GetBudgetsRequestObject struct {
	Params GetBudgetsParams
}

type GetBudgetsResponseObject interface {
	VisitGetBudgetsResponse(w http.ResponseWriter) error
}

type GetBudgets200JSONResponse FetchBudgetListResponse

func (response GetBudgets200JSONResponse) VisitGetBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgets400JSONResponse ErrorBody

func (response GetBudgets400JSONResponse) VisitGetBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgets500JSONResponse ErrorBody

func (response GetBudgets500JSONResponse) VisitGetBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgetsRequestObject struct {
	Body *PostBudgetsJSONRequestBody
}

type PostBudgetsResponseObject interface {
	VisitPostBudgetsResponse(w http.ResponseWriter) error
}

type PostBudgets201JSONResponse CreateBudgetResponse

func (response PostBudgets201JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgets400JSONResponse ErrorBody

func (response PostBudgets400JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgets409JSONResponse ErrorBody

func (response PostBudgets409JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostBudgets500JSONResponse ErrorBody

func (response PostBudgets500JSONResponse) VisitPostBudgetsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteBudgetsIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteBudgetsIdResponseObject interface {
	VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error
}

type DeleteBudgetsId204Response struct {
}

func (response DeleteBudgetsId204Response) VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteBudgetsId404JSONResponse ErrorBody

func (response DeleteBudgetsId404JSONResponse) VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteBudgetsId500JSONResponse ErrorBody

func (response DeleteBudgetsId500JSONResponse) VisitDeleteBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsIdRequestObject struct {
	Id int32 `json:"id"`
}

type GetBudgetsIdResponseObject interface {
	VisitGetBudgetsIdResponse(w http.ResponseWriter) error
}

type GetBudgetsId200JSONResponse FetchBudgetResponse

func (response GetBudgetsId200JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsId400JSONResponse ErrorBody

func (response GetBudgetsId400JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsId404JSONResponse ErrorBody

func (response GetBudgetsId404JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetBudgetsId500JSONResponse ErrorBody

func (response GetBudgetsId500JSONResponse) VisitGetBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PatchBudgetsIdJSONRequestBody
}

type PatchBudgetsIdResponseObject interface {
	VisitPatchBudgetsIdResponse(w http.ResponseWriter) error
}

type PatchBudgetsId200JSONResponse UpdateBudgetResponse

func (response PatchBudgetsId200JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId400JSONResponse ErrorBody

func (response PatchBudgetsId400JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId404JSONResponse ErrorBody

func (response PatchBudgetsId404JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId409JSONResponse ErrorBody

func (response PatchBudgetsId409JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PatchBudgetsId500JSONResponse ErrorBody

func (response PatchBudgetsId500JSONResponse) VisitPatchBudgetsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesRequestObject struct {
}

type GetCategoriesResponseObject interface {
	VisitGetCategoriesResponse(w http.ResponseWriter) error
}

type GetCategories200JSONResponse FetchCategoryListsResponse

func (response GetCategories200JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategories500JSONResponse ErrorBody

func (response GetCategories500JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostCategoriesRequestObject struct {
	Body *PostCategoriesJSONRequestBody
}

type PostCategoriesResponseObject interface {
	VisitPostCategoriesResponse(w http.ResponseWriter) error
}

type PostCategories201JSONResponse CreateCategoryResponse

func (response PostCategories201JSONResponse) VisitPostCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostCategories400JSONResponse ErrorBody

func (response PostCategories400JSONResponse) VisitPostCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostCategories500JSONResponse ErrorBody

func (response PostCategories500JSONResponse) VisitPostCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoriesIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteCategoriesIdResponseObject interface {
	VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error
}

type DeleteCategoriesId204Response struct {
}

func (response DeleteCategoriesId204Response) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCategoriesId400JSONResponse ErrorBody

func (response DeleteCategoriesId400JSONResponse) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoriesId404JSONResponse ErrorBody

func (response DeleteCategoriesId404JSONResponse) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoriesId500JSONResponse ErrorBody

func (response DeleteCategoriesId500JSONResponse) VisitDeleteCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesIdRequestObject struct {
	Id int32 `json:"id"`
}

type GetCategoriesIdResponseObject interface {
	VisitGetCategoriesIdResponse(w http.ResponseWriter) error
}

type GetCategoriesId200JSONResponse FetchCategoryResponse

func (response GetCategoriesId200JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesId400JSONResponse ErrorBody

func (response GetCategoriesId400JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesId404JSONResponse ErrorBody

func (response GetCategoriesId404JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesId500JSONResponse ErrorBody

func (response GetCategoriesId500JSONResponse) VisitGetCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PatchCategoriesIdJSONRequestBody
}

type PatchCategoriesIdResponseObject interface {
	VisitPatchCategoriesIdResponse(w http.ResponseWriter) error
}

type PatchCategoriesId200JSONResponse UpdateCategoryResponse

func (response PatchCategoriesId200JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesId400JSONResponse ErrorBody

func (response PatchCategoriesId400JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesId404JSONResponse ErrorBody

func (response PatchCategoriesId404JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchCategoriesId500JSONResponse ErrorBody

func (response PatchCategoriesId500JSONResponse) VisitPatchCategoriesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrfRequestObject struct {
}

type GetCsrfResponseObject interface {
	VisitGetCsrfResponse(w http.ResponseWriter) error
}

type GetCsrf200JSONResponse CsrfResponse

func (response GetCsrf200JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrf500JSONResponse ErrorBody

func (response GetCsrf500JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsRequestObject struct {
	Params GetTransactionsParams
}

type GetTransactionsResponseObject interface {
	VisitGetTransactionsResponse(w http.ResponseWriter) error
}

type GetTransactions200JSONResponse FetchTransactionListResponse

func (response GetTransactions200JSONResponse) VisitGetTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactions400JSONResponse ErrorBody

func (response GetTransactions400JSONResponse) VisitGetTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactions500JSONResponse ErrorBody

func (response GetTransactions500JSONResponse) VisitGetTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostTransactionsRequestObject struct {
	Body *PostTransactionsJSONRequestBody
}

type PostTransactionsResponseObject interface {
	VisitPostTransactionsResponse(w http.ResponseWriter) error
}

type PostTransactions201JSONResponse CreateTransactionResponse

func (response PostTransactions201JSONResponse) VisitPostTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostTransactions400JSONResponse ErrorBody

func (response PostTransactions400JSONResponse) VisitPostTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostTransactions500JSONResponse ErrorBody

func (response PostTransactions500JSONResponse) VisitPostTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTransactionsIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteTransactionsIdResponseObject interface {
	VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error
}

type DeleteTransactionsId204Response struct {
}

func (response DeleteTransactionsId204Response) VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTransactionsId404JSONResponse ErrorBody

func (response DeleteTransactionsId404JSONResponse) VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTransactionsId500JSONResponse ErrorBody

func (response DeleteTransactionsId500JSONResponse) VisitDeleteTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsIdRequestObject struct {
	Id int32 `json:"id"`
}

type GetTransactionsIdResponseObject interface {
	VisitGetTransactionsIdResponse(w http.ResponseWriter) error
}

type GetTransactionsId200JSONResponse FetchTransactionResponse

func (response GetTransactionsId200JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsId400JSONResponse ErrorBody

func (response GetTransactionsId400JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsId404JSONResponse ErrorBody

func (response GetTransactionsId404JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsId500JSONResponse ErrorBody

func (response GetTransactionsId500JSONResponse) VisitGetTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PatchTransactionsIdJSONRequestBody
}

type PatchTransactionsIdResponseObject interface {
	VisitPatchTransactionsIdResponse(w http.ResponseWriter) error
}

type PatchTransactionsId200JSONResponse UpdateTransactionResponse

func (response PatchTransactionsId200JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsId400JSONResponse ErrorBody

func (response PatchTransactionsId400JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsId404JSONResponse ErrorBody

func (response PatchTransactionsId404JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchTransactionsId500JSONResponse ErrorBody

func (response PatchTransactionsId500JSONResponse) VisitPatchTransactionsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersCheckSignedInRequestObject struct {
}

type GetUsersCheckSignedInResponseObject interface {
	VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error
}

type GetUsersCheckSignedIn200JSONResponse UserUserCheckSignedInResponse

func (response GetUsersCheckSignedIn200JSONResponse) VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignInRequestObject struct {
	Body *PostUsersSignInJSONRequestBody
}

type PostUsersSignInResponseObject interface {
	VisitPostUsersSignInResponse(w http.ResponseWriter) error
}

type PostUsersSignIn200ResponseHeaders struct {
	SetCookie string
}

type PostUsersSignIn200JSONResponse struct {
	Body    UserUserSignInResponse
	Headers PostUsersSignIn200ResponseHeaders
}

func (response PostUsersSignIn200JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("set-cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostUsersSignIn400JSONResponse ErrorBody

func (response PostUsersSignIn400JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignIn401JSONResponse ErrorBody

func (response PostUsersSignIn401JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignIn500JSONResponse ErrorBody

func (response PostUsersSignIn500JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUpRequestObject struct {
	Body *PostUsersSignUpJSONRequestBody
}

type PostUsersSignUpResponseObject interface {
	VisitPostUsersSignUpResponse(w http.ResponseWriter) error
}

type PostUsersSignUp200JSONResponse UserUserSignUpResponse

func (response PostUsersSignUp200JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp400JSONResponse ErrorBody

func (response PostUsersSignUp400JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp409JSONResponse ErrorBody

func (response PostUsersSignUp409JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp500JSONResponse ErrorBody

func (response PostUsersSignUp500JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Budgets
	// (GET /budgets)
	GetBudgets(ctx context.Context, request GetBudgetsRequestObject) (GetBudgetsResponseObject, error)
	// Create Budget
	// (POST /budgets)
	PostBudgets(ctx context.Context, request PostBudgetsRequestObject) (PostBudgetsResponseObject, error)
	// Delete Budget
	// (DELETE /budgets/{id})
	DeleteBudgetsId(ctx context.Context, request DeleteBudgetsIdRequestObject) (DeleteBudgetsIdResponseObject, error)
	// Get Budget
	// (GET /budgets/{id})
	GetBudgetsId(ctx context.Context, request GetBudgetsIdRequestObject) (GetBudgetsIdResponseObject, error)
	// Update Budget
	// (PATCH /budgets/{id})
	PatchBudgetsId(ctx context.Context, request PatchBudgetsIdRequestObject) (PatchBudgetsIdResponseObject, error)
	// Get Categories
	// (GET /categories)
	GetCategories(ctx context.Context, request GetCategoriesRequestObject) (GetCategoriesResponseObject, error)
	// Create Category
	// (POST /categories)
	PostCategories(ctx context.Context, request PostCategoriesRequestObject) (PostCategoriesResponseObject, error)
	// Delete Category
	// (DELETE /categories/{id})
	DeleteCategoriesId(ctx context.Context, request DeleteCategoriesIdRequestObject) (DeleteCategoriesIdResponseObject, error)
	// Get Category
	// (GET /categories/{id})
	GetCategoriesId(ctx context.Context, request GetCategoriesIdRequestObject) (GetCategoriesIdResponseObject, error)
	// Update Category
	// (PATCH /categories/{id})
	PatchCategoriesId(ctx context.Context, request PatchCategoriesIdRequestObject) (PatchCategoriesIdResponseObject, error)
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx context.Context, request GetCsrfRequestObject) (GetCsrfResponseObject, error)
	// Get Transactions
	// (GET /transactions)
	GetTransactions(ctx context.Context, request GetTransactionsRequestObject) (GetTransactionsResponseObject, error)
	// Create Transaction
	// (POST /transactions)
	PostTransactions(ctx context.Context, request PostTransactionsRequestObject) (PostTransactionsResponseObject, error)
	// Delete Transaction
	// (DELETE /transactions/{id})
	DeleteTransactionsId(ctx context.Context, request DeleteTransactionsIdRequestObject) (DeleteTransactionsIdResponseObject, error)
	// Get Transaction
	// (GET /transactions/{id})
	GetTransactionsId(ctx context.Context, request GetTransactionsIdRequestObject) (GetTransactionsIdResponseObject, error)
	// Update Transaction
	// (PATCH /transactions/{id})
	PatchTransactionsId(ctx context.Context, request PatchTransactionsIdRequestObject) (PatchTransactionsIdResponseObject, error)
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx context.Context, request GetUsersCheckSignedInRequestObject) (GetUsersCheckSignedInResponseObject, error)
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx context.Context, request PostUsersSignInRequestObject) (PostUsersSignInResponseObject, error)
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx context.Context, request PostUsersSignUpRequestObject) (PostUsersSignUpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetBudgets operation middleware
func (sh *strictHandler) GetBudgets(ctx echo.Context, params GetBudgetsParams) error {
	var request GetBudgetsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBudgets(ctx.Request().Context(), request.(GetBudgetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBudgets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBudgetsResponseObject); ok {
		return validResponse.VisitGetBudgetsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostBudgets operation middleware
func (sh *strictHandler) PostBudgets(ctx echo.Context) error {
	var request PostBudgetsRequestObject

	var body PostBudgetsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostBudgets(ctx.Request().Context(), request.(PostBudgetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostBudgets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostBudgetsResponseObject); ok {
		return validResponse.VisitPostBudgetsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteBudgetsId operation middleware
func (sh *strictHandler) DeleteBudgetsId(ctx echo.Context, id int32) error {
	var request DeleteBudgetsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBudgetsId(ctx.Request().Context(), request.(DeleteBudgetsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBudgetsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteBudgetsIdResponseObject); ok {
		return validResponse.VisitDeleteBudgetsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBudgetsId operation middleware
func (sh *strictHandler) GetBudgetsId(ctx echo.Context, id int32) error {
	var request GetBudgetsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBudgetsId(ctx.Request().Context(), request.(GetBudgetsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBudgetsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBudgetsIdResponseObject); ok {
		return validResponse.VisitGetBudgetsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchBudgetsId operation middleware
func (sh *strictHandler) PatchBudgetsId(ctx echo.Context, id int32) error {
	var request PatchBudgetsIdRequestObject

	request.Id = id

	var body PatchBudgetsIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchBudgetsId(ctx.Request().Context(), request.(PatchBudgetsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchBudgetsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchBudgetsIdResponseObject); ok {
		return validResponse.VisitPatchBudgetsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategories operation middleware
func (sh *strictHandler) GetCategories(ctx echo.Context) error {
	var request GetCategoriesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategories(ctx.Request().Context(), request.(GetCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesResponseObject); ok {
		return validResponse.VisitGetCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostCategories operation middleware
func (sh *strictHandler) PostCategories(ctx echo.Context) error {
	var request PostCategoriesRequestObject

	var body PostCategoriesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCategories(ctx.Request().Context(), request.(PostCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCategoriesResponseObject); ok {
		return validResponse.VisitPostCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteCategoriesId operation middleware
func (sh *strictHandler) DeleteCategoriesId(ctx echo.Context, id int32) error {
	var request DeleteCategoriesIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCategoriesId(ctx.Request().Context(), request.(DeleteCategoriesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCategoriesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCategoriesIdResponseObject); ok {
		return validResponse.VisitDeleteCategoriesIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategoriesId operation middleware
func (sh *strictHandler) GetCategoriesId(ctx echo.Context, id int32) error {
	var request GetCategoriesIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategoriesId(ctx.Request().Context(), request.(GetCategoriesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategoriesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesIdResponseObject); ok {
		return validResponse.VisitGetCategoriesIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchCategoriesId operation middleware
func (sh *strictHandler) PatchCategoriesId(ctx echo.Context, id int32) error {
	var request PatchCategoriesIdRequestObject

	request.Id = id

	var body PatchCategoriesIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchCategoriesId(ctx.Request().Context(), request.(PatchCategoriesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchCategoriesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchCategoriesIdResponseObject); ok {
		return validResponse.VisitPatchCategoriesIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCsrf operation middleware
func (sh *strictHandler) GetCsrf(ctx echo.Context) error {
	var request GetCsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCsrf(ctx.Request().Context(), request.(GetCsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCsrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCsrfResponseObject); ok {
		return validResponse.VisitGetCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransactions operation middleware
func (sh *strictHandler) GetTransactions(ctx echo.Context, params GetTransactionsParams) error {
	var request GetTransactionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactions(ctx.Request().Context(), request.(GetTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTransactionsResponseObject); ok {
		return validResponse.VisitGetTransactionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostTransactions operation middleware
func (sh *strictHandler) PostTransactions(ctx echo.Context) error {
	var request PostTransactionsRequestObject

	var body PostTransactionsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostTransactions(ctx.Request().Context(), request.(PostTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTransactions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostTransactionsResponseObject); ok {
		return validResponse.VisitPostTransactionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTransactionsId operation middleware
func (sh *strictHandler) DeleteTransactionsId(ctx echo.Context, id int32) error {
	var request DeleteTransactionsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTransactionsId(ctx.Request().Context(), request.(DeleteTransactionsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTransactionsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTransactionsIdResponseObject); ok {
		return validResponse.VisitDeleteTransactionsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransactionsId operation middleware
func (sh *strictHandler) GetTransactionsId(ctx echo.Context, id int32) error {
	var request GetTransactionsIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactionsId(ctx.Request().Context(), request.(GetTransactionsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactionsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTransactionsIdResponseObject); ok {
		return validResponse.VisitGetTransactionsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchTransactionsId operation middleware
func (sh *strictHandler) PatchTransactionsId(ctx echo.Context, id int32) error {
	var request PatchTransactionsIdRequestObject

	request.Id = id

	var body PatchTransactionsIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchTransactionsId(ctx.Request().Context(), request.(PatchTransactionsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchTransactionsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchTransactionsIdResponseObject); ok {
		return validResponse.VisitPatchTransactionsIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUsersCheckSignedIn operation middleware
func (sh *strictHandler) GetUsersCheckSignedIn(ctx echo.Context) error {
	var request GetUsersCheckSignedInRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersCheckSignedIn(ctx.Request().Context(), request.(GetUsersCheckSignedInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersCheckSignedIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersCheckSignedInResponseObject); ok {
		return validResponse.VisitGetUsersCheckSignedInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignIn operation middleware
func (sh *strictHandler) PostUsersSignIn(ctx echo.Context) error {
	var request PostUsersSignInRequestObject

	var body PostUsersSignInJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignIn(ctx.Request().Context(), request.(PostUsersSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignInResponseObject); ok {
		return validResponse.VisitPostUsersSignInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignUp operation middleware
func (sh *strictHandler) PostUsersSignUp(ctx echo.Context) error {
	var request PostUsersSignUpRequestObject

	var body PostUsersSignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignUp(ctx.Request().Context(), request.(PostUsersSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignUpResponseObject); ok {
		return validResponse.VisitPostUsersSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcb3PbRBr/KhrdvaAzbuJCOwd+hZuY4iFxMv5zXKaTyWytTSywJaOVgVwnM9g+Skoo",
	"DRwk9I47KBBaUpoWWjgupPTDqHacV/kKN7sryStp9cclTnyJ32Qief88++zz/PbZ37Ory2JRrVRVBSo6",
	"EhOXRVQswQog/56vSQtQx/9JEBU1uarLqiImrPcxsaqpVajpMiTFQUWtKZziT7aXd7fW925eE2PivKpV",
	"gC4mRFnRn3tWjIn6YhXSR7gANXEpJhaBDhdUbZE0WS5PzYuJi5fFP2pwXkyIfxjtSjtqijo6ZtVYmo25",
	"+jYad4zmFaPx0Ghutpvvtr78ge1iTpa84rJV0uMRZdYg0KE0B3jDf/R5e3m1vb7RvtFgW5OADk/rcgV2",
	"W0S6JisLuEGeYFSPUUWqqIpe8jbSuvdb54eb7c+X93eWZ2ZmZk5PTrYefdXaub6/c1WMiRXw9gRUFnDN",
	"P8XEiqwwTx4ha1XJd9Ttfz5sr93vcdQ1BDX+nDS/NZo7RuNno7kTTQFLMVGDb9RkDUpi4iLWZ7d5pwEw",
	"FhezbNhSn2NmHQOetbtUL70GizoWf4yxXKf8Y90enD5TVMuqFmyDRn2rc/VH59w8G+do71CM8Gm8QwEV",
	"GNxSa/Wac4Bn4vFjZXBEBTFzunu0KlKWYm5aqdY4Y6dFBFpGoIUOBJ0rsiJXahUxcSYIqQ8MRvuOWa5J",
	"csKAy/fD5iILUVVVEAybDruce0Yu2ctr0OJmLrZu0c3K/kJakBNsMlYpH6M5SHg6IBRw6cHhWOHaCJ00",
	"WyG+08bGJ9GiEh+rCxA3rwEFgSIWLXj+mII9+v3eex8NhtNj8OP4/PW11s6n7fUNN5bzYNxR1d1SZ/P7",
	"9mcfugz03DlOM/RF1KiTUX0eV/QGn3QMRuOx0fjGaK7v7yy3rn/YendjtP3JvdZ72xi9ghGJCMQAExl/",
	"JKsJtXPWcHxNXe8WCrN2pj3PoNhmuNIjbZ4V2OVvSJvPq69DIkIInttFcTeyXsZlHa1zek9pmqqdV6VF",
	"njnfNprf4UCg+b3R+K/R/JfRfED++dxovmc0vvZoDOLGwnRFerRFcg+CNjHrJ2lamVcDJO1892D34X1z",
	"q+OW7kXLwl12+u+Vzt3PWssbrburYkyECnb+i0x3szyfUytAVoJ0Vv9g98b27idfGPV1o/6F0bxqNG8S",
	"T3jA8+EK1IEEdEAcUJJk3BwoTzvtMdDxxc7jR633vzTqW6Sjx3iKcAz3eH9n2WjcJdP4q9FcxYtWc8No",
	"7tDwwaNmDQJEDT4aEJjTSSrxdqC2PrZ2V6/sfvKDZ8ZfNP3c7NjWra8NZG0JffqiHRn1rdbWP9qf3mcn",
	"dTKZnphLTmRTyfGZudRf0rl8ToyJ6cyfkxPp8TnyM/M8nczlXp3KYigv5FLZucxUfu6lqUJmnCkzlk2N",
	"pzL5dHICtzSWzKcuTGVnHEXtl+nMXCGXYivbxZOT3PdjUxNTWTEm5rPJTC45lk9PZbhSsL/nZ6bZtpKT",
	"U4VMnnkxnszj388Xxi+k8tzWJqcy+ZeZZ7Oo3ZL17NbjeDKfPJ/MpeZS2SwRu5B5JTP1asZ+Js0liZT0",
	"Fc+3nAARGZY44ZvEqf5yPj9Nql2h7oH/bzwgzV2NuGRDHchlxFlrCfoY9U1bRBuJZB1WUCRkJJBjL8ci",
	"0DSwSBECIbAAeVuY7b21vxv1Dzqbd41G3WisMBq6aTSbRuNXMtRfeMCDdKDXUI/unqOVvO7evn2jvb3W",
	"7d+pZ++KhWeoOzRbGl/Xz9nS9tLv/s7yBVVdKEMhOZ0WcjpQJKBJ7e219sqXFAUtfLB9JnuhMJkitu4x",
	"ctZhplPZyXQuh+15PJVJpwhSZJKF/MsYErAXU7fKp7KZ5ATX2l+CerFEtzkTMgrYV5GC1rYKFw3bW5F/",
	"IxmetctyWx1318WfHmYYEYdw6DtD0ru1L8EKRGGS2tshUjp0U2Q+RVJ5d38UonSm7dBBRR7PEW3viBRM",
	"rBzF4NlQPdjqmUA7+jw4IveQqXB0EGV8vYztqLcheWc3TnHZH3//FnuY9eDv4weGCuCpiMoRVTlHQSYc",
	"y5QMlwRxaqc3Qt2ta5+JtlXNREeyUlSJnuDbVYihihfPFEj3gYQ9LeIg7IVnqkDTZVAWqPinhgy+D4Pv",
	"mVBW4f4LjlPnhx570e5DWHlTRicrH24Zg0nTh6ggdKaOOlajYoRT8aa4Hir+6T16yM0PCjcfbhShZjxI",
	"IW4BQW0kJy8oaT9jxj8Kab9kEqwAucyLBW4SruWO0fiK8LzfUzbKM4tVgNBbqsYNJz4inMU9m4cKpvqp",
	"JEyLgcMtVIOGW6j2abg+WMpEThRL+6gnMz8aXV34z1gJFl/HqoFSOsjAEdQER1l/A5fRHCKF5rhJg+Zd",
	"o3GfJgd23/+5/e5Kd2CXVLUMgdfWHS0GDocafMg4LMMPShU5WixUo7RYqPrrxJfQDGUtXaqwGvJqYSkm",
	"IlisabK+mMP4QTtOVuVX4GKyRkM1PCFiUVVfl6F1UiUh6iSN1qUDSA1xCTcoczNQZlw1BspQkYAmJKfT",
	"YjcJ5/41B7U35SLu702oIdrCmZE4VrJahQqoymJCfG4kPhInRquXiNyjDK3HPZnIupZRv7P7cNWobxj1",
	"6zREfvLLO51vbxmNjzH4/7ZuvNMwGvcIZbqJ3ar5nenYjcdG/ZbR/NRofE2c/DEp8MBo3G9dv9dpPhKJ",
	"kBogMYEkJsQLUD9vSoal1UAF6lBDZJnqKRCGb1fLhLOfB2UEY3Rq3qhBshEyZ8Y6mUbXA25SNHTpj9KP",
	"c0PW7S18nzeLrZPaPJmqZ+NxGqUqOqThDqhWy3KRKHD0NTOV1e0haPXzI4uJZboomxIUsJdApAslgARU",
	"KxYhlKA0gs3s7AEK1U0hc8Q4G48L54EkZE1RTgtWDpKmJ/9jNG8R6zKpe+GZJ7+tJARHRi4muBNyp/AY",
	"zh3WGM7F40Ja0aGmgDLxXagJpAIeTeMnshatktE4B+FMh8UERzbslAOeiLOwwHRxFhsSqlUqAEf42MmE",
	"rpfpYAE5GHm8aqqIR3us3ScZ6L9REDAaH1NuyuPF0ypi3Ni0HOtgwIHo2HuUb8kJ5bpWg0se7znTFwGe",
	"ynUEoEgCEBT4lqBBpNa0IiQFLkGoCCYJIwAkAPxzrawfG1c7G3/hsMbwgjCmKvNluUgHsGk0HtGM3u6d",
	"n1ury27peRn9k4cOjjOXXHxYitnxw+hlWVqiSFGGOvSj1HCkcPX9vRvfeKBinNQzwSItha36zMl9stLi",
	"gKa70JL11YkBv3e9PctJYJSgBgUZCYoqmCYh6KqAoCIJ86om6CUZWT4fEy7VdEEvQaEEgQQ1JFTAonAJ",
	"CjUE52vlEYF6xNnDMS8MRohaVREoiqoL87IiEfFMeaFko9HIibN8aotBlh/jB8umkde3zFMbVlwcEN4O",
	"oKn3JbQ82WHl0LMHLeL1C3iBXiwFrF4047e/s7zXvN1avmI9XvWGvsA2/QHx8YMPvr1puUjBd7wvAgwB",
	"ZkABZhjnDzYmOrK4vnG+8zhaT1Qhy5W5CENeYDTW7anfoQn/4F7PAHLillDHFFn2wh4qDKeOHJn0QALJ",
	"ZQ/94pCc5wiOhEXy5PGHPNKQsuWSMsztd677ORE7lJxxOWMgRdN1x/Cw1pMlOU5czTBoHO5KD5RvCnNq",
	"H9LJfSYtnHr6P3DhPgV6w03i0N8HKoQOcHYfKsq1VvdGSA2m5/eLmXqKkD7eJxGGwDMEnoGheiLtHpA2",
	"78v0jOWyLxnNZSLtPWITZrSxv7Pc2bzWub3z5JdrnW/rPBzC8Qduu4+u5/g+xclkc5xrDdW3Pdf4kc6y",
	"+3pjT7wePfDdzyOAeVa8kOVqb22ldWulvb7RPQd4eny816OASAeaPmeevOcsZPwz+d7zgbs/NZ5sX/m9",
	"0kBFOgBZvAfz6aWrUfPKVXR5zItj0Wzfc2Pg+J+i9LuGPDxKeRJCehdaWXDrvOEdzoxb7hrEibu66h8r",
	"7rmrdSTEOO9y0JAbH/oglxt3flfAxwvdwU8oRW57ZSA5zvpl+A6buf4+PMQ43Ov1hVSO5A0+zLJp85E4",
	"5QG3/P4FekNmZ+jtAxd/BoaffF7ZXuB6Y5QHz+/7xSY/XSgc758UQ+QZIs/AcMqRo+4aghoaLbJ33AOY",
	"R/cl9t2vtjub13gBSAG367g630+KOeRif48e2ZO+PZ8IYPRNlOtQNCI39ck3oLm0g4PcZdTNpR2Ijund",
	"/z6xDp7PaRw2yPp84aC3CY2J5gaJdAz10+a3ABxiuHnbpWMDzGcOawxnhIICanpJ1eS/Qkk4LdDkk5/U",
	"zGeVTx2/TI/9hYwIiFCoRkOE3Ru/7n3wYzAWFKr9xgLrWzNHiQXMt0lOaLg1vMUxGO5N/M3j3iSEwD3T",
	"bVdNK4sJsaTr1cToaFktgnJJRXri+fjzcfLpLrP+ZTuphrR5cSl22ZVkkyFi39LemBeO+I55b90dWZpd",
	"+l8AAAD//znhPpUObwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
