// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Category Category
type Category struct {
	// Color カテゴリの色
	Color string `json:"color"`

	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Id カテゴリID
	Id int32 `json:"id"`

	// Name カテゴリ名
	Name string `json:"name"`

	// UpdatedAt 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// UserId ユーザーID
	UserId int32 `json:"user_id"`
}

// CreateCategoryInput Create Category Input
type CreateCategoryInput struct {
	// Color カテゴリの色
	Color string `json:"color"`

	// Name カテゴリ名
	Name string `json:"name"`
}

// CreateCategoryResponse Create Category Response
type CreateCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// FetchCategoryListsResponse Fetch Category Lists Response
type FetchCategoryListsResponse struct {
	Categories []Category `json:"categories"`
}

// FetchCategoryResponse Fetch Category Response
type FetchCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// UpdateCategoryInput Update Category Input (partial update)
type UpdateCategoryInput struct {
	// Color カテゴリの色
	Color *string `json:"color,omitempty"`

	// Name カテゴリ名
	Name *string `json:"name,omitempty"`
}

// UpdateCategoryResponse Update Category Response
type UpdateCategoryResponse struct {
	// Category Category
	Category Category `json:"category"`
}

// PostCategoriesJSONRequestBody defines body for PostCategories for application/json ContentType.
type PostCategoriesJSONRequestBody = CreateCategoryInput

// PatchCategoriesIdJSONRequestBody defines body for PatchCategoriesId for application/json ContentType.
type PatchCategoriesIdJSONRequestBody = UpdateCategoryInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Categories
	// (GET /categories)
	GetCategories(ctx echo.Context) error
	// Create Category
	// (POST /categories)
	PostCategories(ctx echo.Context) error
	// Delete Category
	// (DELETE /categories/{id})
	DeleteCategoriesId(ctx echo.Context, id int32) error
	// Get Category
	// (GET /categories/{id})
	GetCategoriesId(ctx echo.Context, id int32) error
	// Update Category
	// (PATCH /categories/{id})
	PatchCategoriesId(ctx echo.Context, id int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategories(ctx)
	return err
}

// PostCategories converts echo context to params.
func (w *ServerInterfaceWrapper) PostCategories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCategories(ctx)
	return err
}

// DeleteCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCategoriesId(ctx, id)
	return err
}

// GetCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategoriesId(ctx, id)
	return err
}

// PatchCategoriesId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchCategoriesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchCategoriesId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/categories", wrapper.GetCategories)
	router.POST(baseURL+"/categories", wrapper.PostCategories)
	router.DELETE(baseURL+"/categories/:id", wrapper.DeleteCategoriesId)
	router.GET(baseURL+"/categories/:id", wrapper.GetCategoriesId)
	router.PATCH(baseURL+"/categories/:id", wrapper.PatchCategoriesId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZT2sbRxT/KsO0hxa2luy4EPbWOLQYcghtegomjHeetBN2Z7Yzs26MEVTaEuxCicnB",
	"JrSXQpMmDRTTmBKo2y+zsZKc+hXKzOrfaldaxbVwGnQxkufN2/fn937vvdUO9kQYCQ5cK+zuYOX5EBL7",
	"cY1oaAq5bT5TUJ5kkWaCY3d44uBIigikZmCveCIQsiifdp6myd20c5wmv6bt317t/Y4dHJI714A3tY/d",
	"lbqD9XYE2MVKS8abuOVgTwLRQG8RXVT44q8fu7v73cOH3Qcd7OCGkKERw5Ro+EizEHCJQkanW7Z+dVQV",
	"4/rSylAN4xqaII0eTkKYrul0//u8g8v1Mg/jiE70sPvDcffg6A09jBXIW6VuJo/S5CTt/JEmJ7O52XKw",
	"hK9iJoFi96aJ3VB9LwROL925VOW82hjoFZu3wdPGxjUr20fQOo/iEu8zIdSXQpnYPNF2TkkdC1suTtXR",
	"+BxUJLiC6oAMJAsxGSna9yU0sIvfqw1LvNar79qghMdNHigoM/dT0J7fv3qNKa0mm2xlhxZb6Uq7e9+Y",
	"hlDN7sLAUiIlmeiS0V3p1Mz+XFAGvrTVVVE+mdBY+aAPIiI1IwHKKvTD/0k9VYRgcsLGo3AhGTOijDdE",
	"0bwrMW2CRmskAE6JRJ9cXzc8zHQAJadfgNxinrF9C6TKNCwv1U08RAScRAy7+NJSfalu3CPat57V8mXV",
	"BD29N6Ttpy+P99P2w7R9bzRXL55/8+rRL2nn/um9g9O/D7F9qCRGwzrFLv4M9NrwSSY4WajtU1fq9Qxd",
	"XAO3BpAoCphnr9duK2NFf/CoSsEUArKhzrt2wwdk8gRKI58opGLPA6BAl0zcPn5Du/KgASmzYhmvIVqK",
	"+8dp8sSG+Zn5m+yVte8QlCLNqdeTn9IkSTt/WlXPcVX/sdYMFZfAMy+fOVWO4rxJBo8gUXbBHKs4DImp",
	"IQMGlEODJk01zsMtB0dClQ0+B0dp+zBtf5ujnc79bOQrIO+6UOPQs/m+Iuj2uaGubGZp5WOnZQytAvCX",
	"52TCmUCPCKeIIA5fIwlKxNIDK7AJwFFvhENEIWKO40DbIln970Wiyqqk12kGjb5QDPmOPmwos95ozYR1",
	"NRPYTUhVBnhPxAFFXGgUcwpSaRNUPRJyGgPSAjG+RQJGkdrmmtxZ8M0c+WZsNp5EOC1ntB3WdhhtZZ4H",
	"oCtGFdP49r57/eDnAv1ctbeHBLRObfuVJAQNBvk3KzdOZv5rOnZ/r3KzbSvPLc4IMKqXt40CE60WPbzh",
	"gwTEFOIC9UBpkKuAU9QQEmmfqT6sHbQZa4tzH4jBPQrJNtoEFCtoxMESyrhidQHwswJ8lGMINwTTYHlq",
	"ATrg7QWfzJFPspqu5BNnwjg9ti09efby+GjGyfmtZY85DfBnn91XF9g/H6o5+zizYPsF279b2+oUqo+I",
	"9vzKITF7af/Pye7r5PHp7t3+173i1kqGLPiW8f75b89lryxn2p7rczLhQtvOYhtetI9F+3hn2sfYjwwT",
	"Xz6YS1ZLxu6xDLCLfa0jt1YLhEcCXyjtXq5frmPDwz0lO31uH1HW2mj9GwAA//8brz9rtR8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
