# syntax=docker/dockerfile:1

FROM golang:1.25-alpine

WORKDIR /app

COPY . .

RUN go mod tidy && \
	go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest && \
	go install github.com/air-verse/air@latest

RUN apk add --update make
