/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Budget Calendar Service
 * Budget Calendar API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateCategoryInput,
  CreateCategoryResponse,
  DeleteCategoriesId404,
  ErrorBody,
  FetchCategoryListsResponse,
  FetchCategoryResponse,
  GetCategoriesId404,
  PatchCategoriesId404,
  UpdateCategoryInput,
  UpdateCategoryResponse,
} from ".././model";

import { customFetch } from "../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * ユーザーに紐づくカテゴリ一覧を取得
 * @summary Get Categories
 */
export type getCategoriesResponse200 = {
  data: FetchCategoryListsResponse;
  status: 200;
};

export type getCategoriesResponse500 = {
  data: ErrorBody;
  status: 500;
};

export type getCategoriesResponseSuccess = getCategoriesResponse200 & {
  headers: Headers;
};
export type getCategoriesResponseError = getCategoriesResponse500 & {
  headers: Headers;
};

export type getCategoriesResponse = getCategoriesResponseSuccess | getCategoriesResponseError;

export const getGetCategoriesUrl = () => {
  return `/categories`;
};

export const getCategories = async (options?: RequestInit): Promise<getCategoriesResponse> => {
  return customFetch<getCategoriesResponse>(getGetCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCategoriesQueryKey = () => {
  return [`/categories`] as const;
};

export const getGetCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getCategories>>, TError = ErrorBody>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategories>>> = ({ signal }) => getCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCategories>>>;
export type GetCategoriesQueryError = ErrorBody;

export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = ErrorBody>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>> &
      Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getCategories>>, TError, Awaited<ReturnType<typeof getCategories>>>, "initialData">;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = ErrorBody>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>> &
      Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getCategories>>, TError, Awaited<ReturnType<typeof getCategories>>>, "initialData">;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = ErrorBody>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Categories
 */

export function useGetCategories<TData = Awaited<ReturnType<typeof getCategories>>, TError = ErrorBody>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCategoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 新しいカテゴリを作成
 * @summary Create Category
 */
export type postCategoriesResponse201 = {
  data: CreateCategoryResponse;
  status: 201;
};

export type postCategoriesResponse400 = {
  data: ErrorBody;
  status: 400;
};

export type postCategoriesResponse500 = {
  data: ErrorBody;
  status: 500;
};

export type postCategoriesResponseSuccess = postCategoriesResponse201 & {
  headers: Headers;
};
export type postCategoriesResponseError = (postCategoriesResponse400 | postCategoriesResponse500) & {
  headers: Headers;
};

export type postCategoriesResponse = postCategoriesResponseSuccess | postCategoriesResponseError;

export const getPostCategoriesUrl = () => {
  return `/categories`;
};

export const postCategories = async (createCategoryInput: CreateCategoryInput, options?: RequestInit): Promise<postCategoriesResponse> => {
  return customFetch<postCategoriesResponse>(getPostCategoriesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCategoryInput),
  });
};

export const getPostCategoriesMutationOptions = <TError = ErrorBody | ErrorBody, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postCategories>>, TError, { data: CreateCategoryInput }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof postCategories>>, TError, { data: CreateCategoryInput }, TContext> => {
  const mutationKey = ["postCategories"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCategories>>, { data: CreateCategoryInput }> = (props) => {
    const { data } = props ?? {};

    return postCategories(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof postCategories>>>;
export type PostCategoriesMutationBody = CreateCategoryInput;
export type PostCategoriesMutationError = ErrorBody | ErrorBody;

/**
 * @summary Create Category
 */
export const usePostCategories = <TError = ErrorBody | ErrorBody, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postCategories>>, TError, { data: CreateCategoryInput }, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postCategories>>, TError, { data: CreateCategoryInput }, TContext> => {
  const mutationOptions = getPostCategoriesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * カテゴリの詳細を取得
 * @summary Get Category
 */
export type getCategoriesIdResponse200 = {
  data: FetchCategoryResponse;
  status: 200;
};

export type getCategoriesIdResponse400 = {
  data: ErrorBody;
  status: 400;
};

export type getCategoriesIdResponse404 = {
  data: GetCategoriesId404;
  status: 404;
};

export type getCategoriesIdResponse500 = {
  data: ErrorBody;
  status: 500;
};

export type getCategoriesIdResponseSuccess = getCategoriesIdResponse200 & {
  headers: Headers;
};
export type getCategoriesIdResponseError = (getCategoriesIdResponse400 | getCategoriesIdResponse404 | getCategoriesIdResponse500) & {
  headers: Headers;
};

export type getCategoriesIdResponse = getCategoriesIdResponseSuccess | getCategoriesIdResponseError;

export const getGetCategoriesIdUrl = (id: number) => {
  return `/categories/${id}`;
};

export const getCategoriesId = async (id: number, options?: RequestInit): Promise<getCategoriesIdResponse> => {
  return customFetch<getCategoriesIdResponse>(getGetCategoriesIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetCategoriesIdQueryKey = (id?: number) => {
  return [`/categories/${id}`] as const;
};

export const getGetCategoriesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategoriesId>>,
  TError = ErrorBody | GetCategoriesId404 | ErrorBody,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoriesIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategoriesId>>> = ({ signal }) => getCategoriesId(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetCategoriesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCategoriesId>>>;
export type GetCategoriesIdQueryError = ErrorBody | GetCategoriesId404 | ErrorBody;

export function useGetCategoriesId<TData = Awaited<ReturnType<typeof getCategoriesId>>, TError = ErrorBody | GetCategoriesId404 | ErrorBody>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, Awaited<ReturnType<typeof getCategoriesId>>>,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategoriesId<TData = Awaited<ReturnType<typeof getCategoriesId>>, TError = ErrorBody | GetCategoriesId404 | ErrorBody>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, Awaited<ReturnType<typeof getCategoriesId>>>,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategoriesId<TData = Awaited<ReturnType<typeof getCategoriesId>>, TError = ErrorBody | GetCategoriesId404 | ErrorBody>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get Category
 */

export function useGetCategoriesId<TData = Awaited<ReturnType<typeof getCategoriesId>>, TError = ErrorBody | GetCategoriesId404 | ErrorBody>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesId>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCategoriesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * カテゴリを更新（部分更新）
 * @summary Update Category
 */
export type patchCategoriesIdResponse200 = {
  data: UpdateCategoryResponse;
  status: 200;
};

export type patchCategoriesIdResponse400 = {
  data: ErrorBody;
  status: 400;
};

export type patchCategoriesIdResponse404 = {
  data: PatchCategoriesId404;
  status: 404;
};

export type patchCategoriesIdResponse500 = {
  data: ErrorBody;
  status: 500;
};

export type patchCategoriesIdResponseSuccess = patchCategoriesIdResponse200 & {
  headers: Headers;
};
export type patchCategoriesIdResponseError = (patchCategoriesIdResponse400 | patchCategoriesIdResponse404 | patchCategoriesIdResponse500) & {
  headers: Headers;
};

export type patchCategoriesIdResponse = patchCategoriesIdResponseSuccess | patchCategoriesIdResponseError;

export const getPatchCategoriesIdUrl = (id: number) => {
  return `/categories/${id}`;
};

export const patchCategoriesId = async (
  id: number,
  updateCategoryInput: UpdateCategoryInput,
  options?: RequestInit,
): Promise<patchCategoriesIdResponse> => {
  return customFetch<patchCategoriesIdResponse>(getPatchCategoriesIdUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCategoryInput),
  });
};

export const getPatchCategoriesIdMutationOptions = <TError = ErrorBody | PatchCategoriesId404 | ErrorBody, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof patchCategoriesId>>, TError, { id: number; data: UpdateCategoryInput }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof patchCategoriesId>>, TError, { id: number; data: UpdateCategoryInput }, TContext> => {
  const mutationKey = ["patchCategoriesId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCategoriesId>>, { id: number; data: UpdateCategoryInput }> = (props) => {
    const { id, data } = props ?? {};

    return patchCategoriesId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchCategoriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchCategoriesId>>>;
export type PatchCategoriesIdMutationBody = UpdateCategoryInput;
export type PatchCategoriesIdMutationError = ErrorBody | PatchCategoriesId404 | ErrorBody;

/**
 * @summary Update Category
 */
export const usePatchCategoriesId = <TError = ErrorBody | PatchCategoriesId404 | ErrorBody, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof patchCategoriesId>>, TError, { id: number; data: UpdateCategoryInput }, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof patchCategoriesId>>, TError, { id: number; data: UpdateCategoryInput }, TContext> => {
  const mutationOptions = getPatchCategoriesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * カテゴリを削除
 * @summary Delete Category
 */
export type deleteCategoriesIdResponse204 = {
  data: void;
  status: 204;
};

export type deleteCategoriesIdResponse400 = {
  data: ErrorBody;
  status: 400;
};

export type deleteCategoriesIdResponse404 = {
  data: DeleteCategoriesId404;
  status: 404;
};

export type deleteCategoriesIdResponse500 = {
  data: ErrorBody;
  status: 500;
};

export type deleteCategoriesIdResponseSuccess = deleteCategoriesIdResponse204 & {
  headers: Headers;
};
export type deleteCategoriesIdResponseError = (deleteCategoriesIdResponse400 | deleteCategoriesIdResponse404 | deleteCategoriesIdResponse500) & {
  headers: Headers;
};

export type deleteCategoriesIdResponse = deleteCategoriesIdResponseSuccess | deleteCategoriesIdResponseError;

export const getDeleteCategoriesIdUrl = (id: number) => {
  return `/categories/${id}`;
};

export const deleteCategoriesId = async (id: number, options?: RequestInit): Promise<deleteCategoriesIdResponse> => {
  return customFetch<deleteCategoriesIdResponse>(getDeleteCategoriesIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCategoriesIdMutationOptions = <TError = ErrorBody | DeleteCategoriesId404 | ErrorBody, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCategoriesId>>, TError, { id: number }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteCategoriesId>>, TError, { id: number }, TContext> => {
  const mutationKey = ["deleteCategoriesId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCategoriesId>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteCategoriesId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCategoriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCategoriesId>>>;

export type DeleteCategoriesIdMutationError = ErrorBody | DeleteCategoriesId404 | ErrorBody;

/**
 * @summary Delete Category
 */
export const useDeleteCategoriesId = <TError = ErrorBody | DeleteCategoriesId404 | ErrorBody, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCategoriesId>>, TError, { id: number }, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteCategoriesId>>, TError, { id: number }, TContext> => {
  const mutationOptions = getDeleteCategoriesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
